/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.onMessage(async (message) => { ... });
 *   client.server.createRoom(topic, visibility);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen ./define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, type Unsubscribe, toRpcError, rpcWhenAborted } from "./types.generated";
import type { Visibility, ChatRoom, Message } from "./define";

// === RpcClient INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register the handler for 'onMessage', called by the server. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    onMessage: (handler: (message: Message) => Promise<void>) => Unsubscribe;
    /** Register the handler for 'confirmLeave', called by the server. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    confirmLeave: (handler: (roomId: string) => Promise<boolean>) => Unsubscribe;
}

/** Methods to call server */
export interface RpcClientRemote {
    /** Call server's 'createRoom' method */
    createRoom: (topic: string, visibility: Visibility, opts?: RpcCallOptions) => Promise<ChatRoom | RpcError>;
    /** Call server's 'listRooms' method */
    listRooms: (opts?: RpcCallOptions) => Promise<ChatRoom[] | RpcError>;
    /** Call server's 'postMessage' method */
    postMessage: (roomId: string, body: string, opts?: RpcCallOptions) => Promise<Message | RpcError>;
    /** Call server's 'typing' method */
    typing: (roomId: string, opts?: RpcCallOptions) => void;
}

/**
 * Client RPC interface with ergonomic API.
 *
 * Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup.
 */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientRemote;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => Unsubscribe;
    /** Run a handler on every (re)connect — use it to re-sync or re-authenticate. Returns an unsubscribe function. */
    onConnect: (handler: () => void) => Unsubscribe;
    /** Run a handler after a successful reconnect. Returns an unsubscribe function. */
    onReconnect: (handler: (attempt: number) => void) => Unsubscribe;
    /** Run a handler for errors the peer reports from a fire-and-forget handler. Returns an unsubscribe function. */
    onRpcError: (handler: (error: RpcError) => void) => Unsubscribe;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.onMessage(async (message) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.createRoom(..., ...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): Unsubscribe => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcClientHandle = {
        onMessage(handler: (message: Message) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (message: Message) => {
                try {
                    await handler(message);
                } catch (error) {
                    console.error('[onMessage] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'onMessage' }));
                }
            };
            return register('onMessage', listener);
        },
        confirmLeave(handler: (roomId: string) => Promise<boolean>): Unsubscribe {
            checkDisposed();
            const listener = async (roomId: string, callback: (result: boolean | RpcError) => void) => {
                try {
                    const handlerResult = await handler(roomId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[confirmLeave] Handler error:', error);
                    callback(toRpcError(error, { method: 'confirmLeave' }));
                }
            };
            return register('confirmLeave', listener);
        }
    };

    const server: RpcClientRemote = {
        async createRoom(topic: string, visibility: Visibility, opts?: RpcCallOptions): Promise<ChatRoom | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'createRoom' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'createRoom' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('createRoom', topic, visibility);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'createRoom')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'createRoom' });
            }
        },
        async listRooms(opts?: RpcCallOptions): Promise<ChatRoom[] | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'listRooms' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'listRooms' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('listRooms');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'listRooms')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'listRooms' });
            }
        },
        async postMessage(roomId: string, body: string, opts?: RpcCallOptions): Promise<Message | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'postMessage' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'postMessage' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('postMessage', roomId, body);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'postMessage')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'postMessage' });
            }
        },
        typing(roomId: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('typing', roomId);
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): Unsubscribe {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onConnect(handler: () => void): Unsubscribe {
            checkDisposed();
            socket.on('connect', handler);
            const unsubscribe = () => socket.off('connect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onReconnect(handler: (attempt: number) => void): Unsubscribe {
            checkDisposed();
            socket.io.on('reconnect', handler);
            const unsubscribe = () => socket.io.off('reconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onRpcError(handler: (error: RpcError) => void): Unsubscribe {
            checkDisposed();
            socket.on('__rpc:error__', handler);
            const unsubscribe = () => socket.off('__rpc:error__', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
