/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Users/firegroup/orca/workspaces/socketrpc-gen/socketrpc-v7-integrate/examples/05-go-server/define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, type UnsubscribeFunction, toRpcError, rpcWhenAborted } from "./types.generated";
import type { Visibility, ChatRoom, Message } from "./define";

// === SOCKET EVENT MAPS (optional typing aid) ===
/** Events the client emits and the server listens for. Apply to a typed Socket/Server. */
export interface ClientToServerEvents {
    createRoom: (topic: string, visibility: Visibility, ack: (result: ChatRoom | RpcError) => void) => void;
    listRooms: (ack: (result: ChatRoom[] | RpcError) => void) => void;
    postMessage: (roomId: string, body: string, ack: (result: Message | RpcError) => void) => void;
    typing: (roomId: string) => void;
    "__rpc:error__": (error: RpcError) => void;
}

/** Events the server emits and the client listens for. Apply to a typed Socket/Server. */
export interface ServerToClientEvents {
    onMessage: (message: Message) => void;
    confirmLeave: (roomId: string, ack: (result: boolean | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'onMessage' - called by server. Returns an unsubscribe function. */
    onMessage: (handler: (message: Message) => Promise<void>) => UnsubscribeFunction;
    /** Register handler for 'confirmLeave' - called by server. Returns an unsubscribe function. */
    confirmLeave: (handler: (roomId: string) => Promise<boolean>) => UnsubscribeFunction;
    /** Register handler for RPC errors. Returns an unsubscribe function. */
    rpcError: (handler: (error: RpcError) => void) => UnsubscribeFunction;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'createRoom' method */
    createRoom: (topic: string, visibility: Visibility, opts?: RpcCallOptions) => Promise<ChatRoom | RpcError>;
    /** Call server's 'listRooms' method */
    listRooms: (opts?: RpcCallOptions) => Promise<ChatRoom[] | RpcError>;
    /** Call server's 'postMessage' method */
    postMessage: (roomId: string, body: string, opts?: RpcCallOptions) => Promise<Message | RpcError>;
    /** Call server's 'typing' method */
    typing: (roomId: string, opts?: RpcCallOptions) => void;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => UnsubscribeFunction;
    /** Run a handler on every (re)connect — use it to re-sync or re-authenticate. Returns an unsubscribe function. */
    onConnect: (handler: () => void) => UnsubscribeFunction;
    /** Run a handler after a successful reconnect. Returns an unsubscribe function. */
    onReconnect: (handler: (attempt: number) => void) => UnsubscribeFunction;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.onMessage(async (message) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.createRoom(..., ...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): UnsubscribeFunction => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcClientHandle = {
        onMessage(handler: (message: Message) => Promise<void>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (message: Message) => {
                try {
                    await handler(message);
                } catch (error) {
                    console.error('[onMessage] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'onMessage' }));
                }
            };
            return register('onMessage', listener);
        },
        confirmLeave(handler: (roomId: string) => Promise<boolean>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (roomId: string, callback: (result: boolean | RpcError) => void) => {
                try {
                    const handlerResult = await handler(roomId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[confirmLeave] Handler error:', error);
                    callback(toRpcError(error, { origin: 'confirmLeave' }));
                }
            };
            return register('confirmLeave', listener);
        },
        rpcError(handler: (error: RpcError) => void): UnsubscribeFunction {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            return register('__rpc:error__', listener);
        }
    };

    const server: RpcClientServer = {
        async createRoom(topic: string, visibility: Visibility, opts?: RpcCallOptions): Promise<ChatRoom | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'createRoom' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'createRoom' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('createRoom', topic, visibility);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'createRoom')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'createRoom' });
            }
        },
        async listRooms(opts?: RpcCallOptions): Promise<ChatRoom[] | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'listRooms' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'listRooms' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('listRooms');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'listRooms')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'listRooms' });
            }
        },
        async postMessage(roomId: string, body: string, opts?: RpcCallOptions): Promise<Message | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'postMessage' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'postMessage' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('postMessage', roomId, body);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'postMessage')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'postMessage' });
            }
        },
        typing(roomId: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('typing', roomId);
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onConnect(handler: () => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('connect', handler);
            const unsubscribe = () => socket.off('connect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onReconnect(handler: (attempt: number) => void): UnsubscribeFunction {
            checkDisposed();
            socket.io.on('reconnect', handler);
            const unsubscribe = () => socket.io.off('reconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
