/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/00-full-app/pkg/rpc/define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, toRpcError } from "./types.generated";
import type { GetPlanRequest, Plan } from "./define";

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'showError' - called by server */
    showError: (handler: (error: Error) => Promise<void>) => void;
    /** Register handler for 'updateDiscoveriedUrls' - called by server */
    updateDiscoveriedUrls: (handler: (url: string) => Promise<void>) => void;
    /** Register handler for 'getBrowserVersion' - called by server */
    getBrowserVersion: (handler: () => Promise<string>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'generateText' method */
    generateText: (prompt: string, opts?: RpcCallOptions) => Promise<string | RpcError>;
    /** Call server's 'getPlan' method */
    getPlan: (request: GetPlanRequest, opts?: RpcCallOptions) => Promise<Plan | RpcError>;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.showError(async (error) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.generateText(...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const handle: RpcClientHandle = {
        showError(handler: (error: Error) => Promise<void>) {
            checkDisposed();
            const listener = async (error: Error) => {
                try {
                    await handler(error);
                } catch (error) {
                    console.error('[showError] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'showError' }));
                }
            };
            socket.on('showError', listener);
            unsubscribers.push(() => socket.off('showError', listener));
        },
        updateDiscoveriedUrls(handler: (url: string) => Promise<void>) {
            checkDisposed();
            const listener = async (url: string) => {
                try {
                    await handler(url);
                } catch (error) {
                    console.error('[updateDiscoveriedUrls] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'updateDiscoveriedUrls' }));
                }
            };
            socket.on('updateDiscoveriedUrls', listener);
            unsubscribers.push(() => socket.off('updateDiscoveriedUrls', listener));
        },
        getBrowserVersion(handler: () => Promise<string>) {
            checkDisposed();
            const listener = async (callback: (result: string | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getBrowserVersion] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getBrowserVersion' }));
                }
            };
            socket.on('getBrowserVersion', listener);
            unsubscribers.push(() => socket.off('getBrowserVersion', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('__rpc:error__', listener);
            unsubscribers.push(() => socket.off('__rpc:error__', listener));
        }
    };

    const server: RpcClientServer = {
        async generateText(prompt: string, opts?: RpcCallOptions): Promise<string | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'generateText' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('generateText', prompt);
            } catch (err) {
                return toRpcError(err, { origin: 'generateText' });
            }
        },
        async getPlan(request: GetPlanRequest, opts?: RpcCallOptions): Promise<Plan | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getPlan' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('getPlan', request);
            } catch (err) {
                return toRpcError(err, { origin: 'getPlan' });
            }
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
