/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.handle.eventName(async (data) => { ... });
 *   server.client.methodName(args);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/00-full-app/pkg/rpc/define.ts
 */

import type { Socket } from "socket.io";
import type { RpcError } from "./types.generated";
import type { GetPlanRequest, Plan } from "./define";

// === RPCSERVER INTERFACE ===
/** Handler registration methods - implement these to handle calls from client */
export interface RpcServerHandle {
    /** Register handler for 'generateText' - called by client */
    generateText: (handler: (prompt: string) => Promise<string | RpcError>) => void;
    /** Register handler for 'getPlan' - called by client */
    getPlan: (handler: (request: GetPlanRequest) => Promise<Plan | RpcError>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call client */
export interface RpcServerClient {
    /** Call client's 'showError' method */
    showError: (error: Error) => void;
    /** Call client's 'updateDiscoveriedUrls' method */
    updateDiscoveriedUrls: (url: string) => void;
    /** Call client's 'getBrowserVersion' method */
    getBrowserVersion: (timeout?: number) => Promise<string | RpcError>;
}

/** Server RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.client` to call client methods, and `.dispose()` to cleanup. */
export interface RpcServer {
    /** Register handlers for calls from client */
    readonly handle: RpcServerHandle;
    /** Call client methods */
    readonly client: RpcServerClient;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers for calls from client
 * server.handle.generateText(async (prompt) => {
 *   // handle event
 * });
 *
 * // Call client methods
 * server.client.showError(...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .handle, .client, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const handle: RpcServerHandle = {
        generateText(handler: (prompt: string) => Promise<string | RpcError>) {
            checkDisposed();
            const listener = async (prompt: string, callback: (result: string | RpcError) => void) => {
                try {
                    const result = await handler(prompt);
                    callback(result);
                } catch (error) {
                    console.error('[generateText] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('generateText', listener);
            unsubscribers.push(() => socket.off('generateText', listener));
        },
        getPlan(handler: (request: GetPlanRequest) => Promise<Plan | RpcError>) {
            checkDisposed();
            const listener = async (request: GetPlanRequest, callback: (result: Plan | RpcError) => void) => {
                try {
                    const result = await handler(request);
                    callback(result);
                } catch (error) {
                    console.error('[getPlan] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('getPlan', listener);
            unsubscribers.push(() => socket.off('getPlan', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('rpcError', listener);
            unsubscribers.push(() => socket.off('rpcError', listener));
        }
    };

    const client: RpcServerClient = {
        showError(error: Error) {
            socket.emit('showError', error);
        },
        updateDiscoveriedUrls(url: string) {
            socket.emit('updateDiscoveriedUrls', url);
        },
        async getBrowserVersion(timeout: number = 5000): Promise<string | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('getBrowserVersion');
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        }
    };

    return {
        handle,
        client,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
