/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/02-single-extension/define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, toRpcError } from "./types.generated";
import type { Product, CreateProductRequest } from "./define";

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'showError' - called by server */
    showError: (handler: (error: Error) => Promise<void>) => void;
    /** Register handler for 'showSuccess' - called by server */
    showSuccess: (handler: (message: string) => Promise<void>) => void;
    /** Register handler for 'getClientInfo' - called by server */
    getClientInfo: (handler: () => Promise<{ userAgent: string; language: string; }>) => void;
    /** Register handler for 'onProductUpdated' - called by server */
    onProductUpdated: (handler: (product: Product) => Promise<void>) => void;
    /** Register handler for 'refreshProducts' - called by server */
    refreshProducts: (handler: () => Promise<void>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'ping' method */
    ping: (opts?: RpcCallOptions) => Promise<string | RpcError>;
    /** Call server's 'getServerTime' method */
    getServerTime: (opts?: RpcCallOptions) => Promise<number | RpcError>;
    /** Call server's 'getProduct' method */
    getProduct: (productId: string, opts?: RpcCallOptions) => Promise<Product | RpcError>;
    /** Call server's 'createProduct' method */
    createProduct: (request: CreateProductRequest, opts?: RpcCallOptions) => Promise<Product | RpcError>;
    /** Call server's 'listProducts' method */
    listProducts: (opts?: RpcCallOptions) => Promise<Product[] | RpcError>;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.showError(async (error) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.ping();
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const handle: RpcClientHandle = {
        showError(handler: (error: Error) => Promise<void>) {
            checkDisposed();
            const listener = async (error: Error) => {
                try {
                    await handler(error);
                } catch (error) {
                    console.error('[showError] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'showError' }));
                }
            };
            socket.on('showError', listener);
            unsubscribers.push(() => socket.off('showError', listener));
        },
        showSuccess(handler: (message: string) => Promise<void>) {
            checkDisposed();
            const listener = async (message: string) => {
                try {
                    await handler(message);
                } catch (error) {
                    console.error('[showSuccess] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'showSuccess' }));
                }
            };
            socket.on('showSuccess', listener);
            unsubscribers.push(() => socket.off('showSuccess', listener));
        },
        getClientInfo(handler: () => Promise<{ userAgent: string; language: string; }>) {
            checkDisposed();
            const listener = async (callback: (result: { userAgent: string; language: string; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getClientInfo] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getClientInfo' }));
                }
            };
            socket.on('getClientInfo', listener);
            unsubscribers.push(() => socket.off('getClientInfo', listener));
        },
        onProductUpdated(handler: (product: Product) => Promise<void>) {
            checkDisposed();
            const listener = async (product: Product) => {
                try {
                    await handler(product);
                } catch (error) {
                    console.error('[onProductUpdated] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'onProductUpdated' }));
                }
            };
            socket.on('onProductUpdated', listener);
            unsubscribers.push(() => socket.off('onProductUpdated', listener));
        },
        refreshProducts(handler: () => Promise<void>) {
            checkDisposed();
            const listener = async () => {
                try {
                    await handler();
                } catch (error) {
                    console.error('[refreshProducts] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'refreshProducts' }));
                }
            };
            socket.on('refreshProducts', listener);
            unsubscribers.push(() => socket.off('refreshProducts', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('__rpc:error__', listener);
            unsubscribers.push(() => socket.off('__rpc:error__', listener));
        }
    };

    const server: RpcClientServer = {
        async ping(opts?: RpcCallOptions): Promise<string | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'ping' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('ping');
            } catch (err) {
                return toRpcError(err, { origin: 'ping' });
            }
        },
        async getServerTime(opts?: RpcCallOptions): Promise<number | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getServerTime' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('getServerTime');
            } catch (err) {
                return toRpcError(err, { origin: 'getServerTime' });
            }
        },
        async getProduct(productId: string, opts?: RpcCallOptions): Promise<Product | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getProduct' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('getProduct', productId);
            } catch (err) {
                return toRpcError(err, { origin: 'getProduct' });
            }
        },
        async createProduct(request: CreateProductRequest, opts?: RpcCallOptions): Promise<Product | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'createProduct' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('createProduct', request);
            } catch (err) {
                return toRpcError(err, { origin: 'createProduct' });
            }
        },
        async listProducts(opts?: RpcCallOptions): Promise<Product[] | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'listProducts' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('listProducts');
            } catch (err) {
                return toRpcError(err, { origin: 'listProducts' });
            }
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
