/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.handle.eventName(async (data) => { ... });
 *   server.client.methodName(args);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/02-single-extension/define.ts
 */

import type { Socket } from "socket.io";
import { type RpcError, type RpcCallOptions, type UnsubscribeFunction, toRpcError, rpcWhenAborted } from "./types.generated";
import type { Product, CreateProductRequest } from "./define";

// === SOCKET EVENT MAPS (optional typing aid) ===
/** Events the client emits and the server listens for. Apply to a typed Socket/Server. */
export interface ClientToServerEvents {
    ping: (ack: (result: string | RpcError) => void) => void;
    getServerTime: (ack: (result: number | RpcError) => void) => void;
    getProduct: (productId: string, ack: (result: Product | RpcError) => void) => void;
    createProduct: (request: CreateProductRequest, ack: (result: Product | RpcError) => void) => void;
    listProducts: (ack: (result: Product[] | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

/** Events the server emits and the client listens for. Apply to a typed Socket/Server. */
export interface ServerToClientEvents {
    showError: (error: Error) => void;
    showSuccess: (message: string) => void;
    getClientInfo: (ack: (result: { userAgent: string; language: string; } | RpcError) => void) => void;
    onProductUpdated: (product: Product) => void;
    refreshProducts: () => void;
    "__rpc:error__": (error: RpcError) => void;
}

// === RPCSERVER INTERFACE ===
/** Handler registration methods - implement these to handle calls from client */
export interface RpcServerHandle {
    /** Register handler for 'ping' - called by client. Returns an unsubscribe function. */
    ping: (handler: () => Promise<string>) => UnsubscribeFunction;
    /** Register handler for 'getServerTime' - called by client. Returns an unsubscribe function. */
    getServerTime: (handler: () => Promise<number>) => UnsubscribeFunction;
    /** Register handler for 'getProduct' - called by client. Returns an unsubscribe function. */
    getProduct: (handler: (productId: string) => Promise<Product>) => UnsubscribeFunction;
    /** Register handler for 'createProduct' - called by client. Returns an unsubscribe function. */
    createProduct: (handler: (request: CreateProductRequest) => Promise<Product>) => UnsubscribeFunction;
    /** Register handler for 'listProducts' - called by client. Returns an unsubscribe function. */
    listProducts: (handler: () => Promise<Product[]>) => UnsubscribeFunction;
    /** Register handler for RPC errors. Returns an unsubscribe function. */
    rpcError: (handler: (error: RpcError) => void) => UnsubscribeFunction;
}

/** Methods to call client */
export interface RpcServerClient {
    /** Call client's 'showError' method */
    showError: (error: Error, opts?: RpcCallOptions) => void;
    /** Call client's 'showSuccess' method */
    showSuccess: (message: string, opts?: RpcCallOptions) => void;
    /** Call client's 'getClientInfo' method */
    getClientInfo: (opts?: RpcCallOptions) => Promise<{ userAgent: string; language: string; } | RpcError>;
    /** Call client's 'onProductUpdated' method */
    onProductUpdated: (product: Product, opts?: RpcCallOptions) => void;
    /** Call client's 'refreshProducts' method */
    refreshProducts: (opts?: RpcCallOptions) => void;
}

/** Server RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.client` to call client methods, and `.dispose()` to cleanup. */
export interface RpcServer {
    /** Register handlers for calls from client */
    readonly handle: RpcServerHandle;
    /** Call client methods */
    readonly client: RpcServerClient;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => UnsubscribeFunction;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers for calls from client
 * server.handle.ping(async (data) => {
 *   // handle event
 * });
 *
 * // Call client methods
 * server.client.showError(...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .handle, .client, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): UnsubscribeFunction => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcServerHandle = {
        ping(handler: () => Promise<string>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (callback: (result: string | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[ping] Handler error:', error);
                    callback(toRpcError(error, { origin: 'ping' }));
                }
            };
            return register('ping', listener);
        },
        getServerTime(handler: () => Promise<number>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (callback: (result: number | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getServerTime] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getServerTime' }));
                }
            };
            return register('getServerTime', listener);
        },
        getProduct(handler: (productId: string) => Promise<Product>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (productId: string, callback: (result: Product | RpcError) => void) => {
                try {
                    const handlerResult = await handler(productId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getProduct] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getProduct' }));
                }
            };
            return register('getProduct', listener);
        },
        createProduct(handler: (request: CreateProductRequest) => Promise<Product>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (request: CreateProductRequest, callback: (result: Product | RpcError) => void) => {
                try {
                    const handlerResult = await handler(request);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[createProduct] Handler error:', error);
                    callback(toRpcError(error, { origin: 'createProduct' }));
                }
            };
            return register('createProduct', listener);
        },
        listProducts(handler: () => Promise<Product[]>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (callback: (result: Product[] | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[listProducts] Handler error:', error);
                    callback(toRpcError(error, { origin: 'listProducts' }));
                }
            };
            return register('listProducts', listener);
        },
        rpcError(handler: (error: RpcError) => void): UnsubscribeFunction {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            return register('__rpc:error__', listener);
        }
    };

    const client: RpcServerClient = {
        showError(error: Error, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('showError', error);
        },
        showSuccess(message: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('showSuccess', message);
        },
        async getClientInfo(opts?: RpcCallOptions): Promise<{ userAgent: string; language: string; } | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getClientInfo' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'getClientInfo' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('getClientInfo');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'getClientInfo')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'getClientInfo' });
            }
        },
        onProductUpdated(product: Product, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onProductUpdated', product);
        },
        refreshProducts(opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('refreshProducts');
        }
    };

    return {
        handle,
        client,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
