/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated types for the RPC package
 *
 * To regenerate this file, run:
 * bunx socketrpc-gen ./define.ts
 */

import type { Product, CreateProductRequest } from "./define";

/** Function to unsubscribe from an event listener. Call this to clean up the listener. */
export type Unsubscribe = () => void;

/** Per-call options for RPC methods. Extensible — new fields can be added without breaking callers. */
export interface RpcCallOptions {
    /** Override the default timeout (ms) for this call. Ignored for fire-and-forget calls. */
    timeout?: number;
    /** Abort the call. When the signal fires, the call settles with an ABORTED RpcError and stops awaiting the acknowledgement. */
    signal?: AbortSignal;
    /** Drop the call instead of buffering it when the socket is disconnected. Use for real-time or non-idempotent calls that must not be replayed on reconnect. */
    volatile?: boolean;
}

/** Standard RPC error codes. Use these instead of ad-hoc strings. */
export const RpcErrorCodes = {
    TIMEOUT: "TIMEOUT",
    DISPOSED: "DISPOSED",
    DISCONNECTED: "DISCONNECTED",
    ABORTED: "ABORTED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    INVALID_ARGUMENT: "INVALID_ARGUMENT",
} as const;

/** Union of all standard RPC error code string literals. */
export type RpcErrorCode = typeof RpcErrorCodes[keyof typeof RpcErrorCodes];

/** Represents an error that occurred during an RPC call. */
export interface RpcError {
    /** Brand marking this object as an RpcError. Set by `toRpcError`/`rpcError`; checked by `isRpcError`. Distinguishes errors from successful results that happen to share the `{ message, code }` shape. */
    readonly __rpcError: true;
    /** The error message. */
    message: string;
    /** The error code. Standard codes are in RpcErrorCodes. */
    code: string;
    /** Name of the RPC method where the error originated. */
    method?: string;
    /** Optional error-specific payload. */
    data?: any;
}

/** Type guard to check if a value is an RpcError. Relies on the `__rpcError` brand, so successful results that share the `{ message, code }` shape are never misclassified. */
export function isRpcError(obj: any): obj is RpcError {
    return !!obj && (obj as RpcError).__rpcError === true;
}

/** Construct a branded RpcError. Use inside handlers to signal a typed failure, e.g. `throw rpcError('NOT_FOUND', 'User not found')`. */
export function rpcError(code: string, message: string, data?: any): RpcError {
    return { __rpcError: true, code, message, data };
}

/** Normalize any thrown value into a branded RpcError. Passes existing RpcError values through unchanged, and maps socket.io's timeout and disconnect errors to the TIMEOUT and DISCONNECTED codes. */
export function toRpcError(err: unknown, opts?: { code?: string; method?: string }): RpcError {
    if (isRpcError(err)) return err;
    const message = err instanceof Error ? err.message : String(err);
    const isTimeout = err instanceof Error && err.message === "operation has timed out";
    const isDisconnected = err instanceof Error && err.message === "socket has been disconnected";
    const code = opts?.code ?? (isTimeout
        ? RpcErrorCodes.TIMEOUT
        : isDisconnected
            ? RpcErrorCodes.DISCONNECTED
            : RpcErrorCodes.INTERNAL_ERROR);
    return { __rpcError: true, message, code, method: opts?.method };
}

/** Resolve with an ABORTED RpcError when the signal fires. Internal helper raced against in-flight calls so an aborted call stops awaiting its acknowledgement. */
export function rpcWhenAborted(signal: AbortSignal, method: string): Promise<RpcError> {
    return new Promise((resolve) => {
        const fire = () => resolve({ __rpcError: true, code: RpcErrorCodes.ABORTED, message: "Request aborted", method });
        if (signal.aborted) return fire();
        signal.addEventListener("abort", fire, { once: true });
    });
}

// === SOCKET EVENT MAPS (optional typing aid) ===
/** Events the client emits and the server listens for. Apply to a typed Socket/Server. */
export interface ClientToServerEvents {
    ping: (ack: (result: string | RpcError) => void) => void;
    getServerTime: (ack: (result: number | RpcError) => void) => void;
    getProduct: (productId: string, ack: (result: Product | RpcError) => void) => void;
    createProduct: (request: CreateProductRequest, ack: (result: Product | RpcError) => void) => void;
    listProducts: (ack: (result: Product[] | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

/** Events the server emits and the client listens for. Apply to a typed Socket/Server. */
export interface ServerToClientEvents {
    showError: (error: Error) => void;
    showSuccess: (message: string) => void;
    getClientInfo: (ack: (result: { userAgent: string; language: string; } | RpcError) => void) => void;
    onProductUpdated: (product: Product) => void;
    refreshProducts: () => void;
    "__rpc:error__": (error: RpcError) => void;
}
