/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen ./define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, type UnsubscribeFunction, toRpcError, rpcWhenAborted } from "./types.generated";
import type { Echo, Receipt } from "./define";

// === SOCKET EVENT MAPS (optional typing aid) ===
/** Events the client emits and the server listens for. Apply to a typed Socket/Server. */
export interface ClientToServerEvents {
    echo: (id: string, payload: string, ack: (result: Echo | RpcError) => void) => void;
    failTyped: (reason: string, ack: (result: Echo | RpcError) => void) => void;
    note: (text: string) => void;
    readNotes: (ack: (result: string[] | RpcError) => void) => void;
    neverAck: (id: string, ack: (result: Echo | RpcError) => void) => void;
    dropWhileInFlight: (id: string, ack: (result: Echo | RpcError) => void) => void;
    receipt: (id: string, ack: (result: Receipt | RpcError) => void) => void;
    roundTrip: (question: string, ack: (result: string | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

/** Events the server emits and the client listens for. Apply to a typed Socket/Server. */
export interface ServerToClientEvents {
    notify: (text: string) => void;
    ask: (question: string, ack: (result: string | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'notify' - called by server. Returns an unsubscribe function. */
    notify: (handler: (text: string) => Promise<void>) => UnsubscribeFunction;
    /** Register handler for 'ask' - called by server. Returns an unsubscribe function. */
    ask: (handler: (question: string) => Promise<string>) => UnsubscribeFunction;
    /** Register handler for RPC errors. Returns an unsubscribe function. */
    rpcError: (handler: (error: RpcError) => void) => UnsubscribeFunction;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'echo' method */
    echo: (id: string, payload: string, opts?: RpcCallOptions) => Promise<Echo | RpcError>;
    /** Call server's 'failTyped' method */
    failTyped: (reason: string, opts?: RpcCallOptions) => Promise<Echo | RpcError>;
    /** Call server's 'note' method */
    note: (text: string, opts?: RpcCallOptions) => void;
    /** Call server's 'readNotes' method */
    readNotes: (opts?: RpcCallOptions) => Promise<string[] | RpcError>;
    /** Call server's 'neverAck' method */
    neverAck: (id: string, opts?: RpcCallOptions) => Promise<Echo | RpcError>;
    /** Call server's 'dropWhileInFlight' method */
    dropWhileInFlight: (id: string, opts?: RpcCallOptions) => Promise<Echo | RpcError>;
    /** Call server's 'receipt' method */
    receipt: (id: string, opts?: RpcCallOptions) => Promise<Receipt | RpcError>;
    /** Call server's 'roundTrip' method */
    roundTrip: (question: string, opts?: RpcCallOptions) => Promise<string | RpcError>;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => UnsubscribeFunction;
    /** Run a handler on every (re)connect — use it to re-sync or re-authenticate. Returns an unsubscribe function. */
    onConnect: (handler: () => void) => UnsubscribeFunction;
    /** Run a handler after a successful reconnect. Returns an unsubscribe function. */
    onReconnect: (handler: (attempt: number) => void) => UnsubscribeFunction;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.notify(async (text) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.echo(..., ...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): UnsubscribeFunction => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcClientHandle = {
        notify(handler: (text: string) => Promise<void>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (text: string) => {
                try {
                    await handler(text);
                } catch (error) {
                    console.error('[notify] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'notify' }));
                }
            };
            return register('notify', listener);
        },
        ask(handler: (question: string) => Promise<string>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (question: string, callback: (result: string | RpcError) => void) => {
                try {
                    const handlerResult = await handler(question);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[ask] Handler error:', error);
                    callback(toRpcError(error, { origin: 'ask' }));
                }
            };
            return register('ask', listener);
        },
        rpcError(handler: (error: RpcError) => void): UnsubscribeFunction {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            return register('__rpc:error__', listener);
        }
    };

    const server: RpcClientServer = {
        async echo(id: string, payload: string, opts?: RpcCallOptions): Promise<Echo | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'echo' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'echo' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('echo', id, payload);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'echo')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'echo' });
            }
        },
        async failTyped(reason: string, opts?: RpcCallOptions): Promise<Echo | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'failTyped' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'failTyped' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('failTyped', reason);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'failTyped')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'failTyped' });
            }
        },
        note(text: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('note', text);
        },
        async readNotes(opts?: RpcCallOptions): Promise<string[] | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'readNotes' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'readNotes' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('readNotes');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'readNotes')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'readNotes' });
            }
        },
        async neverAck(id: string, opts?: RpcCallOptions): Promise<Echo | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'neverAck' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'neverAck' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('neverAck', id);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'neverAck')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'neverAck' });
            }
        },
        async dropWhileInFlight(id: string, opts?: RpcCallOptions): Promise<Echo | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'dropWhileInFlight' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'dropWhileInFlight' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('dropWhileInFlight', id);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'dropWhileInFlight')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'dropWhileInFlight' });
            }
        },
        async receipt(id: string, opts?: RpcCallOptions): Promise<Receipt | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'receipt' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'receipt' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('receipt', id);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'receipt')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'receipt' });
            }
        },
        async roundTrip(question: string, opts?: RpcCallOptions): Promise<string | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'roundTrip' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'roundTrip' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('roundTrip', question);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'roundTrip')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'roundTrip' });
            }
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onConnect(handler: () => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('connect', handler);
            const unsubscribe = () => socket.off('connect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onReconnect(handler: (attempt: number) => void): UnsubscribeFunction {
            checkDisposed();
            socket.io.on('reconnect', handler);
            const unsubscribe = () => socket.io.off('reconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
