// Code generated by socketrpc-gen. DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	socket "github.com/zishang520/socket.io/servers/socket/v3"
)

// Socket.IO carries the ack timeout as a flag mutated on the socket and
// consumed by the next Emit, so two concurrent calls on one connection can
// steal each other's timeout. Every emit the generated code performs is
// serialized through the per-socket lock below to keep that pairing intact.
type rpc_socketEmitState struct {
	mu   sync.Mutex
	refs int
}

var rpc_socketEmitStates = struct {
	sync.Mutex
	states map[*socket.Socket]*rpc_socketEmitState
}{states: make(map[*socket.Socket]*rpc_socketEmitState)}

func rpc_acquireSocketEmitState(rawSocket *socket.Socket) *rpc_socketEmitState {
	rpc_socketEmitStates.Lock()
	defer rpc_socketEmitStates.Unlock()
	shared := rpc_socketEmitStates.states[rawSocket]
	if shared == nil {
		shared = &rpc_socketEmitState{}
		rpc_socketEmitStates.states[rawSocket] = shared
	}
	shared.refs++
	return shared
}

func rpc_releaseSocketEmitState(rawSocket *socket.Socket, shared *rpc_socketEmitState) {
	if rawSocket == nil || shared == nil {
		return
	}
	rpc_socketEmitStates.Lock()
	defer rpc_socketEmitStates.Unlock()
	if rpc_socketEmitStates.states[rawSocket] != shared {
		return
	}
	shared.refs--
	if shared.refs == 0 {
		delete(rpc_socketEmitStates.states, rawSocket)
	}
}

type rpc_eventQueue struct {
	run func([]any)

	mu      sync.Mutex
	pending [][]any
	running bool
}

func rpc_newEventQueue(run func([]any)) *rpc_eventQueue {
	return &rpc_eventQueue{run: run}
}

// push never blocks: the Socket.IO listener must stay free to deliver the
// next packet even while this method's handler is still running.
func (q *rpc_eventQueue) push(args []any) {
	q.mu.Lock()
	q.pending = append(q.pending, args)
	if q.running {
		q.mu.Unlock()
		return
	}
	q.running = true
	q.mu.Unlock()
	go q.drain()
}

func (q *rpc_eventQueue) drain() {
	for {
		q.mu.Lock()
		if len(q.pending) == 0 {
			q.running = false
			q.mu.Unlock()
			return
		}
		next := q.pending[0]
		q.pending = q.pending[1:]
		q.mu.Unlock()
		q.run(next)
	}
}

// queuedListener gives one event its own queue. Building it here rather than
// in BindServer keeps the registration site free of per-method locals, so the
// only contract-derived identifiers in that scope are struct field selectors.
func rpc_queuedListener(run func([]any)) func(...any) {
	queue := rpc_newEventQueue(run)
	return func(rawArgs ...any) {
		queue.push(append([]any(nil), rawArgs...))
	}
}

type ServerHandler interface {
	HandleCreateRoom(ctx context.Context, topic string, visibility Visibility) (ChatRoom, error)
	HandleListRooms(ctx context.Context) ([]ChatRoom, error)
	HandlePostMessage(ctx context.Context, roomID string, body string) (Message, error)
	HandleTyping(ctx context.Context, roomID string) error
}

type ServerBinding struct {
	rpc_socket    *socket.Socket
	rpc_emitState *rpc_socketEmitState
	rpc_handler   ServerHandler
	rpc_ctx       context.Context
	rpc_cancel    context.CancelFunc

	rpc_mu               sync.RWMutex
	rpc_disposed         bool
	rpc_errorObservers   []rpc_errorSubscription
	rpc_errorObserverSeq uint64
	rpc_disposeOnce      sync.Once

	listenCreateRoom     func(...any)
	listenListRooms      func(...any)
	listenPostMessage    func(...any)
	listenTyping         func(...any)
	rpc_listenRpcError   func(...any)
	rpc_listenDisconnect func(...any)
}

func BindServer(rawSocket *socket.Socket, handler ServerHandler) (*ServerBinding, error) {
	if rawSocket == nil {
		return nil, NewRpcError(CodeInvalidArgument, "socket must not be nil", "BindServer", nil)
	}
	if handler == nil {
		return nil, NewRpcError(CodeInvalidArgument, "handler must not be nil", "BindServer", nil)
	}
	ctx, cancel := context.WithCancel(context.Background())
	binding := &ServerBinding{
		rpc_socket:    rawSocket,
		rpc_emitState: rpc_acquireSocketEmitState(rawSocket),
		rpc_handler:   handler,
		rpc_ctx:       ctx,
		rpc_cancel:    cancel,
	}

	binding.listenCreateRoom = rpc_queuedListener(binding.handleCreateRoom)
	if err := rawSocket.On("createRoom", binding.listenCreateRoom); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register createRoom: %w", err)
	}
	binding.listenListRooms = rpc_queuedListener(binding.handleListRooms)
	if err := rawSocket.On("listRooms", binding.listenListRooms); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register listRooms: %w", err)
	}
	binding.listenPostMessage = rpc_queuedListener(binding.handlePostMessage)
	if err := rawSocket.On("postMessage", binding.listenPostMessage); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register postMessage: %w", err)
	}
	binding.listenTyping = rpc_queuedListener(binding.handleTyping)
	if err := rawSocket.On("typing", binding.listenTyping); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register typing: %w", err)
	}

	// The peer reports a failed fire-and-forget handler out of band, because
	// such a call has no acknowledgement to answer through.
	binding.rpc_listenRpcError = rpc_queuedListener(binding.rpc_handleRpcError)
	if err := rawSocket.On(RPCErrorEvent, binding.rpc_listenRpcError); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register %s: %w", RPCErrorEvent, err)
	}
	binding.rpc_listenDisconnect = func(...any) {
		binding.Dispose()
	}
	if err := rawSocket.On("disconnect", binding.rpc_listenDisconnect); err != nil {
		binding.Dispose()
		return nil, fmt.Errorf("register disconnect: %w", err)
	}
	return binding, nil
}

func (b *ServerBinding) Context() context.Context {
	return b.rpc_ctx
}

func (b *ServerBinding) Disposed() bool {
	b.rpc_mu.RLock()
	defer b.rpc_mu.RUnlock()
	return b.rpc_disposed
}

// OnRpcError observes the failures the peer reports out of band: a client
// whose handler for a fire-and-forget server-to-client call fails has no
// acknowledgement to answer through, so it emits the error instead. Without
// an observer here that report is dropped and this side never learns of it.
//
// Observers are additive and run in registration order, matching the
// TypeScript client's onRpcError. Call the returned function to unsubscribe.
func (b *ServerBinding) OnRpcError(handler func(*RpcError)) func() {
	if b == nil || handler == nil {
		return func() {}
	}
	b.rpc_mu.Lock()
	b.rpc_errorObserverSeq++
	id := b.rpc_errorObserverSeq
	b.rpc_errorObservers = append(b.rpc_errorObservers, rpc_errorSubscription{id: id, fn: handler})
	b.rpc_mu.Unlock()
	return func() {
		b.rpc_mu.Lock()
		defer b.rpc_mu.Unlock()
		for i, sub := range b.rpc_errorObservers {
			if sub.id == id {
				b.rpc_errorObservers = append(b.rpc_errorObservers[:i], b.rpc_errorObservers[i+1:]...)
				return
			}
		}
	}
}

func (b *ServerBinding) rpc_handleRpcError(rawArgs []any) {
	b.rpc_mu.RLock()
	// Snapshot under the lock: an observer is free to subscribe or
	// unsubscribe from inside the callback without deadlocking.
	observers := append([]rpc_errorSubscription(nil), b.rpc_errorObservers...)
	disposed := b.rpc_disposed
	b.rpc_mu.RUnlock()
	if len(observers) == 0 || disposed || len(rawArgs) == 0 {
		return
	}
	failure, ok := rpc_decodeRpcError(rawArgs[0])
	if !ok {
		failure = NewRpcError(CodeInternalError, fmt.Sprint(rawArgs[0]), RPCErrorEvent, nil)
	}
	for _, sub := range observers {
		// An observer that panics must not take the queue goroutine down with
		// it, nor stop the observers registered after it.
		func() {
			defer func() {
				_ = recover()
			}()
			sub.fn(failure)
		}()
	}
}

func (b *ServerBinding) Dispose() {
	if b == nil {
		return
	}
	b.rpc_disposeOnce.Do(func() {
		if b.rpc_emitState != nil {
			b.rpc_emitState.mu.Lock()
			defer b.rpc_emitState.mu.Unlock()
		}
		b.rpc_mu.Lock()
		b.rpc_disposed = true
		// Drop the observers too, so Dispose releases every closure the
		// caller handed over — the same contract as the client's dispose().
		b.rpc_errorObservers = nil
		b.rpc_mu.Unlock()
		b.rpc_cancel()
		if b.rpc_socket != nil && b.listenCreateRoom != nil {
			b.rpc_socket.RemoveListener("createRoom", b.listenCreateRoom)
		}
		if b.rpc_socket != nil && b.listenListRooms != nil {
			b.rpc_socket.RemoveListener("listRooms", b.listenListRooms)
		}
		if b.rpc_socket != nil && b.listenPostMessage != nil {
			b.rpc_socket.RemoveListener("postMessage", b.listenPostMessage)
		}
		if b.rpc_socket != nil && b.listenTyping != nil {
			b.rpc_socket.RemoveListener("typing", b.listenTyping)
		}
		if b.rpc_socket != nil && b.rpc_listenRpcError != nil {
			b.rpc_socket.RemoveListener(RPCErrorEvent, b.rpc_listenRpcError)
		}
		if b.rpc_socket != nil && b.rpc_listenDisconnect != nil {
			b.rpc_socket.RemoveListener("disconnect", b.rpc_listenDisconnect)
		}
		rpc_releaseSocketEmitState(b.rpc_socket, b.rpc_emitState)
	})
}

func (b *ServerBinding) rpc_emitError(err *RpcError) {
	if err == nil || b.rpc_socket == nil || b.rpc_emitState == nil || b.Disposed() {
		return
	}
	// Data is caller-supplied and may not encode; the report must survive it.
	if rpc_ensureEncodable(err, err.Method) != nil {
		err = NewRpcError(err.Code, err.Message, err.Method, nil)
	}
	b.rpc_emitState.mu.Lock()
	defer b.rpc_emitState.mu.Unlock()
	if !b.rpc_socket.Connected() || b.Disposed() {
		return
	}
	_ = b.rpc_socket.Emit(RPCErrorEvent, err)
}

type rpc_errorSubscription struct {
	id uint64
	fn func(*RpcError)
}

type rpc_inboundCall struct {
	binding *ServerBinding
	method  string
	ack     socket.Ack
	args    []any
	once    sync.Once
}

// beginInbound splits the acknowledgement callback off the raw argument list
// and checks arity. It returns nil when the event cannot be carried any
// further, having already reported why.
func rpc_beginInbound(b *ServerBinding, method string, want int, wantAck bool, rawArgs []any) *rpc_inboundCall {
	pending := &rpc_inboundCall{binding: b, method: method}
	args := rawArgs
	if wantAck {
		if len(args) == 0 {
			b.rpc_emitError(NewRpcError(CodeInvalidArgument, "missing acknowledgement callback", method, nil))
			return nil
		}
		callback, isAck := args[len(args)-1].(socket.Ack)
		if !isAck {
			b.rpc_emitError(NewRpcError(CodeInvalidArgument, "missing acknowledgement callback", method, nil))
			return nil
		}
		pending.ack = callback
		args = args[:len(args)-1]
	}
	if len(args) != want {
		pending.fail(CodeInvalidArgument, fmt.Sprintf("expected %d arguments, got %d", want, len(args)))
		return nil
	}
	pending.args = args
	return pending
}

// reply answers exactly once. A fire-and-forget call has no acknowledgement
// slot, so its failures travel on the out-of-band error event instead.
func (c *rpc_inboundCall) reply(value any) {
	if c.ack == nil {
		if failure, ok := value.(*RpcError); ok {
			c.binding.rpc_emitError(failure)
		}
		return
	}
	c.once.Do(func() {
		c.ack([]any{value}, nil)
	})
}

func (c *rpc_inboundCall) fail(code RpcErrorCode, message string) {
	c.reply(NewRpcError(code, message, c.method, nil))
}

// recoverPanic is deferred directly by the handler, which is what lets the
// builtin recover see a panic unwinding through it.
func (c *rpc_inboundCall) recoverPanic() {
	if value := recover(); value != nil {
		c.reply(rpc_errorFromPanic(value, c.method))
	}
}

func (c *rpc_inboundCall) ready() bool {
	if c.binding.Disposed() {
		c.fail(CodeDisposed, "server binding is disposed")
		return false
	}
	return true
}

func (c *rpc_inboundCall) decode(index int, target any, name string) bool {
	if err := rpc_decodeValue(c.args[index], target); err != nil {
		c.fail(CodeInvalidArgument, fmt.Sprintf("invalid argument %s: %v", name, err))
		return false
	}
	return true
}

func (c *rpc_inboundCall) finish(value any, err error) {
	if err != nil {
		c.reply(rpc_errorFromError(err, c.method))
		return
	}
	if failure := rpc_ensureEncodable(value, c.method); failure != nil {
		c.reply(failure)
		return
	}
	c.reply(value)
}

func (c *rpc_inboundCall) finishVoid(err error) {
	if err != nil {
		c.reply(rpc_errorFromError(err, c.method))
	}
}

func (b *ServerBinding) handleCreateRoom(rawArgs []any) {
	call := rpc_beginInbound(b, "createRoom", 2, true, rawArgs)
	if call == nil {
		return
	}
	defer call.recoverPanic()
	if !call.ready() {
		return
	}
	var arg0 string
	if !call.decode(0, &arg0, "topic") {
		return
	}
	var arg1 Visibility
	if !call.decode(1, &arg1, "visibility") {
		return
	}
	call.finish(b.rpc_handler.HandleCreateRoom(b.rpc_ctx, arg0, arg1))
}

func (b *ServerBinding) handleListRooms(rawArgs []any) {
	call := rpc_beginInbound(b, "listRooms", 0, true, rawArgs)
	if call == nil {
		return
	}
	defer call.recoverPanic()
	if !call.ready() {
		return
	}
	result, err := b.rpc_handler.HandleListRooms(b.rpc_ctx)
	if err == nil && result == nil {
		result = []ChatRoom{}
	}
	call.finish(result, err)
}

func (b *ServerBinding) handlePostMessage(rawArgs []any) {
	call := rpc_beginInbound(b, "postMessage", 2, true, rawArgs)
	if call == nil {
		return
	}
	defer call.recoverPanic()
	if !call.ready() {
		return
	}
	var arg0 string
	if !call.decode(0, &arg0, "roomId") {
		return
	}
	var arg1 string
	if !call.decode(1, &arg1, "body") {
		return
	}
	call.finish(b.rpc_handler.HandlePostMessage(b.rpc_ctx, arg0, arg1))
}

func (b *ServerBinding) handleTyping(rawArgs []any) {
	call := rpc_beginInbound(b, "typing", 1, false, rawArgs)
	if call == nil {
		return
	}
	defer call.recoverPanic()
	if !call.ready() {
		return
	}
	var arg0 string
	if !call.decode(0, &arg0, "roomId") {
		return
	}
	call.finishVoid(b.rpc_handler.HandleTyping(b.rpc_ctx, arg0))
}

type ClientOptions struct {
	Timeout time.Duration
}

type rpc_ackResult struct {
	args []any
	err  error
}

type Client struct {
	socket    *socket.Socket
	emitState *rpc_socketEmitState
	timeout   time.Duration

	mu sync.RWMutex

	disposed     bool
	disconnected bool
	done         chan struct{}
	doneOnce     sync.Once
	releaseOnce  sync.Once

	listenDisconnect func(...any)
}

func NewClient(rawSocket *socket.Socket, options *ClientOptions) (*Client, error) {
	if rawSocket == nil {
		return nil, NewRpcError(CodeInvalidArgument, "socket must not be nil", "NewClient", nil)
	}
	if options != nil && options.Timeout < 0 {
		return nil, NewRpcError(CodeInvalidArgument, "timeout must not be negative", "NewClient", nil)
	}
	timeout := 5000 * time.Millisecond
	if options != nil && options.Timeout > 0 {
		timeout = options.Timeout
	}
	client := &Client{
		socket:    rawSocket,
		emitState: rpc_acquireSocketEmitState(rawSocket),
		timeout:   timeout,
		done:      make(chan struct{}),
	}
	client.listenDisconnect = func(...any) {
		client.markDisconnected()
	}
	if err := rawSocket.On("disconnect", client.listenDisconnect); err != nil {
		client.releaseEmitState()
		return nil, fmt.Errorf("register disconnect: %w", err)
	}
	if !rawSocket.Connected() {
		client.markDisconnected()
		rawSocket.RemoveListener("disconnect", client.listenDisconnect)
		return nil, NewRpcError(CodeDisconnected, "socket is disconnected", "NewClient", nil)
	}
	return client, nil
}

func (c *Client) Socket() *socket.Socket {
	return c.socket
}

func (c *Client) Done() <-chan struct{} {
	return c.done
}

func (c *Client) Connected() bool {
	if c == nil {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	return !c.disposed && !c.disconnected && c.socket != nil && c.socket.Connected()
}

func (c *Client) markDisconnected() {
	c.emitState.mu.Lock()
	defer c.emitState.mu.Unlock()
	c.mu.Lock()
	c.disconnected = true
	c.mu.Unlock()
	c.doneOnce.Do(func() {
		close(c.done)
	})
	if c.socket != nil && c.listenDisconnect != nil {
		c.socket.RemoveListener("disconnect", c.listenDisconnect)
	}
	c.releaseEmitState()
}

func (c *Client) releaseEmitState() {
	c.releaseOnce.Do(func() {
		rpc_releaseSocketEmitState(c.socket, c.emitState)
	})
}

func (c *Client) stateError(method string) *RpcError {
	c.mu.RLock()
	defer c.mu.RUnlock()
	if c.disposed {
		return NewRpcError(CodeDisposed, "client is disposed", method, nil)
	}
	if c.disconnected || c.socket == nil || !c.socket.Connected() {
		return NewRpcError(CodeDisconnected, "socket is disconnected", method, nil)
	}
	return nil
}

func (c *Client) Dispose() {
	if c == nil {
		return
	}
	c.emitState.mu.Lock()
	defer c.emitState.mu.Unlock()
	c.mu.Lock()
	if c.disposed {
		c.mu.Unlock()
		return
	}
	c.disposed = true
	c.mu.Unlock()
	c.doneOnce.Do(func() {
		close(c.done)
	})
	if c.socket != nil && c.listenDisconnect != nil {
		c.socket.RemoveListener("disconnect", c.listenDisconnect)
	}
	c.releaseEmitState()
}

func rpc_errorFromContext(ctx context.Context, method string) *RpcError {
	if ctx == nil {
		return NewRpcError(CodeInvalidArgument, "context must not be nil", method, nil)
	}
	if err := ctx.Err(); err != nil {
		if errors.Is(err, context.DeadlineExceeded) {
			return NewRpcError(CodeTimeout, err.Error(), method, nil)
		}
		return NewRpcError(CodeAborted, err.Error(), method, nil)
	}
	return nil
}

func rpc_errorFromTransport(err error, method string) *RpcError {
	if err == nil {
		return nil
	}
	if err.Error() == "operation has timed out" {
		return NewRpcError(CodeTimeout, err.Error(), method, nil)
	}
	if err.Error() == "socket has been disconnected" {
		return NewRpcError(CodeDisconnected, err.Error(), method, nil)
	}
	return NewRpcError(CodeInternalError, err.Error(), method, nil)
}

// emit performs one fire-and-forget call.
func rpc_emit(c *Client, ctx context.Context, method string, args ...any) error {
	if err := rpc_errorFromContext(ctx, method); err != nil {
		return err
	}
	if err := rpc_ensureEncodable(args, method); err != nil {
		return err
	}
	c.emitState.mu.Lock()
	defer c.emitState.mu.Unlock()
	if err := c.stateError(method); err != nil {
		return err
	}
	if err := c.socket.Emit(method, args...); err != nil {
		return rpc_errorFromTransport(err, method)
	}
	return nil
}

// request performs one acknowledged call and decodes the answer into target.
func rpc_request(c *Client, ctx context.Context, method string, target any, args ...any) error {
	if err := rpc_errorFromContext(ctx, method); err != nil {
		return err
	}
	if err := rpc_ensureEncodable(args, method); err != nil {
		return err
	}
	response := make(chan rpc_ackResult, 1)
	c.emitState.mu.Lock()
	if err := c.stateError(method); err != nil {
		c.emitState.mu.Unlock()
		return err
	}
	c.socket.Timeout(c.timeout).EmitWithAck(method, args...)(func(values []any, err error) {
		select {
		case response <- rpc_ackResult{args: values, err: err}:
		default:
		}
	})
	c.emitState.mu.Unlock()

	var acknowledged rpc_ackResult
	select {
	case <-ctx.Done():
		return rpc_errorFromContext(ctx, method)
	case <-c.done:
		return c.stateError(method)
	case acknowledged = <-response:
	}
	if acknowledged.err != nil {
		return rpc_errorFromTransport(acknowledged.err, method)
	}
	if len(acknowledged.args) != 1 {
		message := fmt.Sprintf("expected one acknowledgement value, got %d", len(acknowledged.args))
		return NewRpcError(CodeInvalidArgument, message, method, nil)
	}
	if failure, ok := rpc_decodeRpcError(acknowledged.args[0]); ok {
		return failure
	}
	if err := rpc_decodeInto(acknowledged.args[0], target); err != nil {
		message := fmt.Sprintf("invalid acknowledgement payload: %v", err)
		return NewRpcError(CodeInvalidArgument, message, method, nil)
	}
	return nil
}

func (rpc_c *Client) CallOnMessage(ctx context.Context, message Message) error {
	return rpc_emit(rpc_c, ctx, "onMessage", message)
}

func (rpc_c *Client) CallConfirmLeave(ctx context.Context, roomID string) (rpc_result bool, rpc_err error) {
	rpc_err = rpc_request(rpc_c, ctx, "confirmLeave", &rpc_result, roomID)
	return
}
