// Code generated by socketrpc-gen. DO NOT EDIT.

package rpc

import (
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
)

const RPCErrorEvent = "__rpc:error__"

type RpcErrorCode string

const (
	CodeTimeout         RpcErrorCode = "TIMEOUT"
	CodeDisposed        RpcErrorCode = "DISPOSED"
	CodeDisconnected    RpcErrorCode = "DISCONNECTED"
	CodeAborted         RpcErrorCode = "ABORTED"
	CodeInternalError   RpcErrorCode = "INTERNAL_ERROR"
	CodeInvalidArgument RpcErrorCode = "INVALID_ARGUMENT"
)

type RpcError struct {
	RPCError bool         `json:"__rpcError"`
	Code     RpcErrorCode `json:"code"`
	Message  string       `json:"message"`
	Method   string       `json:"method,omitempty"`
	Data     any          `json:"data,omitempty"`
}

func (e *RpcError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if e.Method == "" {
		return fmt.Sprintf("%s: %s", e.Code, e.Message)
	}
	return fmt.Sprintf("%s (%s): %s", e.Code, e.Method, e.Message)
}

func NewRpcError(code RpcErrorCode, message string, method string, data any) *RpcError {
	return &RpcError{RPCError: true, Code: code, Message: message, Method: method, Data: data}
}

func IsRpcError(err error) bool {
	var rpcErr *RpcError
	return errors.As(err, &rpcErr) && rpcErr != nil && rpcErr.RPCError
}

func rpc_errorFromError(err error, method string) *RpcError {
	var rpcErr *RpcError
	if errors.As(err, &rpcErr) && rpcErr != nil {
		clone := *rpcErr
		clone.RPCError = true
		if clone.Method == "" {
			clone.Method = method
		}
		return &clone
	}
	return NewRpcError(CodeInternalError, err.Error(), method, nil)
}

func rpc_errorFromPanic(value any, method string) *RpcError {
	return NewRpcError(CodeInternalError, fmt.Sprint(value), method, nil)
}

// A payload the JSON encoder refuses would be dropped by Socket.IO's write
// path without an error anywhere, leaving the peer to wait out its own
// timeout. Checking before the value is handed over turns that silence into
// an immediate answer that names the offending value — the common cause
// being a required string enum left at its zero value.
func rpc_ensureEncodable(value any, method string) *RpcError {
	if _, err := json.Marshal(value); err != nil {
		return NewRpcError(CodeInternalError, fmt.Sprintf("cannot encode payload: %v", err), method, nil)
	}
	return nil
}

func rpc_decodeValue(value any, target any) error {
	encoded, err := json.Marshal(value)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(encoded, target); err != nil {
		return err
	}
	return nil
}

// decodeInto leaves target at its zero value when the payload does not fit,
// so a failed call still yields the zero result a caller expects alongside
// the error rather than a half-populated one.
func rpc_decodeInto(value any, target any) error {
	if err := rpc_decodeValue(value, target); err != nil {
		pointer := reflect.ValueOf(target)
		if pointer.Kind() == reflect.Pointer && !pointer.IsNil() {
			pointer.Elem().Set(reflect.Zero(pointer.Elem().Type()))
		}
		return err
	}
	return nil
}

func rpc_decodeRpcError(value any) (*RpcError, bool) {
	var rpcErr RpcError
	if err := rpc_decodeValue(value, &rpcErr); err != nil {
		return nil, false
	}
	if !rpcErr.RPCError {
		return nil, false
	}
	return &rpcErr, true
}

type Visibility string

const (
	VisibilityPublic  Visibility = "public"
	VisibilityPrivate Visibility = "private"
)

func (v Visibility) Valid() bool {
	switch v {
	case VisibilityPublic, VisibilityPrivate:
		return true
	default:
		return false
	}
}

func (v Visibility) MarshalJSON() ([]byte, error) {
	if !v.Valid() {
		return nil, fmt.Errorf("invalid Visibility %q", v)
	}
	return json.Marshal(string(v))
}

func (v *Visibility) UnmarshalJSON(data []byte) error {
	if v == nil {
		return fmt.Errorf("cannot unmarshal Visibility into nil receiver")
	}
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	candidate := Visibility(raw)
	if !candidate.Valid() {
		return fmt.Errorf("invalid Visibility %q", raw)
	}
	*v = candidate
	return nil
}

type ChatRoom struct {
	ID          string     `json:"id"`
	Topic       string     `json:"topic"`
	MemberCount float64    `json:"memberCount"`
	Visibility  Visibility `json:"visibility"`
}

type Message struct {
	ID       string  `json:"id"`
	RoomID   string  `json:"roomId"`
	Body     string  `json:"body"`
	SentAt   string  `json:"sentAt"`
	EditedAt *string `json:"editedAt,omitempty"`
}
