import { exportedIdentifier, goString, localIdentifier, padGoColumn } from "./names";
import {
  DEFAULT_GO_SOCKET_IMPORT,
  GO_SERVER_FILENAME,
  GO_TYPES_FILENAME,
  type GeneratedGoFiles,
  type GoEmitterOptions,
  type GoEmitterSchema,
  type GoObjectField,
  type GoRpcMethod,
  type GoTypeRef,
} from "./schema";
import { validateGoEmitterSchema } from "./validate";

const GENERATED_HEADER = `// Code generated by socketrpc-gen. DO NOT EDIT.\n`;

class GoWriter {
  readonly #lines: string[] = [];
  #indent = 0;

  line(value = ""): void {
    this.#lines.push(value ? `${"\t".repeat(this.#indent)}${value}` : "");
  }

  block(firstLine: string, body: () => void, lastLine = "}"): void {
    this.line(`${firstLine} {`);
    this.#indent += 1;
    body();
    this.#indent -= 1;
    this.line(lastLine);
  }

  toString(): string {
    return `${this.#lines.join("\n")}\n`;
  }
}

function goType(ref: GoTypeRef): string {
  switch (ref.kind) {
    case "scalar":
      switch (ref.name) {
        case "string":
          return "string";
        case "boolean":
          return "bool";
        case "number":
          return "float64";
        case "integer":
          return "int64";
      }
    case "named":
      return ref.name;
    case "array":
      return `[]${goType(ref.element)}`;
    case "map":
      return `map[string]${goType(ref.value)}`;
    case "nullable":
      return `*${goType(ref.value)}`;
  }
}

function methodName(method: GoRpcMethod): string {
  return method.goName ?? exportedIdentifier(method.name);
}

function paramName(param: GoRpcMethod["params"][number]): string {
  return param.goName ?? localIdentifier(param.name);
}

function fieldName(field: GoObjectField): string {
  return field.goName ?? exportedIdentifier(field.name);
}

function listenerField(method: GoRpcMethod): string {
  return `listen${methodName(method)}`;
}

function methodParameters(method: GoRpcMethod): string {
  return method.params.map((param) => `${paramName(param)} ${goType(param.type)}`).join(", ");
}

function handlerParameters(method: GoRpcMethod): string {
  const params = methodParameters(method);
  return params ? `ctx context.Context, ${params}` : "ctx context.Context";
}

function callArguments(method: GoRpcMethod): string {
  const params = method.params.map(paramName).join(", ");
  return params ? `b.ctx, ${params}` : "b.ctx";
}

function emitArguments(method: GoRpcMethod): string {
  const params = method.params.map(paramName).join(", ");
  return params ? `, ${params}` : "";
}

function writeTypesFile(schema: GoEmitterSchema): string {
  const writer = new GoWriter();
  writer.line(GENERATED_HEADER.trimEnd());
  writer.line();
  writer.line(`package ${schema.packageName}`);
  writer.line();
  writer.line("import (");
  writer.line('\t"encoding/json"');
  writer.line('\t"errors"');
  writer.line('\t"fmt"');
  writer.line(")");
  writer.line();
  writer.line('const RPCErrorEvent = "__rpc:error__"');
  writer.line();
  writer.line("type RpcErrorCode string");
  writer.line();
  writer.line("const (");
  writer.line('\tCodeTimeout         RpcErrorCode = "TIMEOUT"');
  writer.line('\tCodeDisposed        RpcErrorCode = "DISPOSED"');
  writer.line('\tCodeDisconnected    RpcErrorCode = "DISCONNECTED"');
  writer.line('\tCodeAborted         RpcErrorCode = "ABORTED"');
  writer.line('\tCodeInternalError   RpcErrorCode = "INTERNAL_ERROR"');
  writer.line('\tCodeInvalidArgument RpcErrorCode = "INVALID_ARGUMENT"');
  writer.line(")");
  writer.line();
  writer.block("type RpcError struct", () => {
    writer.line('RPCError bool         `json:"__rpcError"`');
    writer.line('Code     RpcErrorCode `json:"code"`');
    writer.line('Message  string       `json:"message"`');
    writer.line('Origin   string       `json:"origin,omitempty"`');
    writer.line('Data     any          `json:"data,omitempty"`');
  });
  writer.line();
  writer.block("func (e *RpcError) Error() string", () => {
    writer.block("if e == nil", () => writer.line('return "<nil>"'));
    writer.block("if e.Origin == \"\"", () => writer.line("return fmt.Sprintf(\"%s: %s\", e.Code, e.Message)"));
    writer.line("return fmt.Sprintf(\"%s (%s): %s\", e.Code, e.Origin, e.Message)");
  });
  writer.line();
  writer.block(
    "func NewRpcError(code RpcErrorCode, message string, origin string, data any) *RpcError",
    () => writer.line("return &RpcError{RPCError: true, Code: code, Message: message, Origin: origin, Data: data}"),
  );
  writer.line();
  writer.block("func IsRpcError(err error) bool", () => {
    writer.line("var rpcErr *RpcError");
    writer.line("return errors.As(err, &rpcErr) && rpcErr != nil && rpcErr.RPCError");
  });
  writer.line();
  writer.block("func rpcErrorFromError(err error, origin string) *RpcError", () => {
    writer.line("var rpcErr *RpcError");
    writer.block("if errors.As(err, &rpcErr) && rpcErr != nil", () => {
      writer.line("copy := *rpcErr");
      writer.line("copy.RPCError = true");
      writer.block("if copy.Origin == \"\"", () => writer.line("copy.Origin = origin"));
      writer.line("return &copy");
    });
    writer.line("return NewRpcError(CodeInternalError, err.Error(), origin, nil)");
  });
  writer.line();
  writer.block("func rpcErrorFromPanic(value any, origin string) *RpcError", () => {
    writer.line("return NewRpcError(CodeInternalError, fmt.Sprint(value), origin, nil)");
  });
  writer.line();
  writer.block("func decodeValue(value any, target any) error", () => {
    writer.line("encoded, err := json.Marshal(value)");
    writer.block("if err != nil", () => writer.line("return err"));
    writer.block("if err := json.Unmarshal(encoded, target); err != nil", () => writer.line("return err"));
    writer.line("return nil");
  });
  writer.line();
  writer.block("func decodeRpcError(value any) (*RpcError, bool)", () => {
    writer.line("var rpcErr RpcError");
    writer.block("if err := decodeValue(value, &rpcErr); err != nil", () => writer.line("return nil, false"));
    writer.block("if !rpcErr.RPCError", () => writer.line("return nil, false"));
    writer.line("return &rpcErr, true");
  });

  for (const declaration of schema.declarations) {
    writer.line();
    if (declaration.kind === "enum") {
      writer.line(`type ${declaration.name} string`);
      writer.line();
      writer.line("const (");
      const constants = declaration.values.map(
        (value) => `${declaration.name}${exportedIdentifier(value)}`,
      );
      const constantWidth = Math.max(...constants.map((constant) => constant.length));
      for (const [index, value] of declaration.values.entries()) {
        writer.line(`\t${padGoColumn(constants[index]!, constantWidth)}${declaration.name} = ${goString(value)}`);
      }
      writer.line(")");
      writer.line();
      writer.block(`func (v ${declaration.name}) Valid() bool`, () => {
        writer.line("switch v {");
        writer.line(`case ${constants.join(", ")}:`);
        writer.line("\treturn true");
        writer.line("default:");
        writer.line("\treturn false");
        writer.line("}");
      });
      writer.line();
      writer.block(`func (v ${declaration.name}) MarshalJSON() ([]byte, error)`, () => {
        writer.block("if !v.Valid()", () => {
          writer.line(`return nil, fmt.Errorf("invalid ${declaration.name} %q", v)`);
        });
        writer.line("return json.Marshal(string(v))");
      });
      writer.line();
      writer.block(`func (v *${declaration.name}) UnmarshalJSON(data []byte) error`, () => {
        writer.block("if v == nil", () => {
          writer.line(`return fmt.Errorf("cannot unmarshal ${declaration.name} into nil receiver")`);
        });
        writer.line("var raw string");
        writer.block("if err := json.Unmarshal(data, &raw); err != nil", () => writer.line("return err"));
        writer.line(`candidate := ${declaration.name}(raw)`);
        writer.block("if !candidate.Valid()", () => {
          writer.line(`return fmt.Errorf("invalid ${declaration.name} %q", raw)`);
        });
        writer.line("*v = candidate");
        writer.line("return nil");
      });
      continue;
    }

    const fields = declaration.fields.map((field) => ({
      field,
      name: fieldName(field),
      type: field.optional ? `*${goType(field.type)}` : goType(field.type),
    }));
    const nameWidth = Math.max(0, ...fields.map((field) => field.name.length));
    const typeWidth = Math.max(0, ...fields.map((field) => field.type.length));
    if (fields.length === 0) {
      writer.line(`type ${declaration.name} struct{}`);
    } else {
      writer.block(`type ${declaration.name} struct`, () => {
        for (const rendered of fields) {
          const omitempty = rendered.field.optional ? ",omitempty" : "";
          writer.line(
            `${padGoColumn(rendered.name, nameWidth)}${padGoColumn(rendered.type, typeWidth)}\`json:${goString(`${rendered.field.name}${omitempty}`)}\``,
          );
        }
      });
    }
  }

  return writer.toString();
}

function writeHandlerInterface(writer: GoWriter, methods: readonly GoRpcMethod[]): void {
  if (methods.length === 0) {
    writer.line("type ServerHandler interface{}");
    return;
  }
  writer.block("type ServerHandler interface", () => {
    for (const method of methods) {
      const result = method.result ? ` (${goType(method.result)}, error)` : " error";
      writer.line(`${methodName(method)}(${handlerParameters(method)})${result}`);
    }
  });
}

function writeSocketEmitState(writer: GoWriter): void {
  writer.block("type socketEmitState struct", () => {
    writer.line("mu   sync.Mutex");
    writer.line("refs int");
  });
  writer.line();
  writer.line("var socketEmitStates = struct {");
  writer.line("\tsync.Mutex");
  writer.line("\tstates map[*socket.Socket]*socketEmitState");
  writer.line("}{states: make(map[*socket.Socket]*socketEmitState)}");
  writer.line();
  writer.block("func acquireSocketEmitState(rawSocket *socket.Socket) *socketEmitState", () => {
    writer.line("socketEmitStates.Lock()");
    writer.line("defer socketEmitStates.Unlock()");
    writer.line("state := socketEmitStates.states[rawSocket]");
    writer.block("if state == nil", () => {
      writer.line("state = &socketEmitState{}");
      writer.line("socketEmitStates.states[rawSocket] = state");
    });
    writer.line("state.refs++");
    writer.line("return state");
  });
  writer.line();
  writer.block("func releaseSocketEmitState(rawSocket *socket.Socket, state *socketEmitState)", () => {
    writer.block("if rawSocket == nil || state == nil", () => writer.line("return"));
    writer.line("socketEmitStates.Lock()");
    writer.line("defer socketEmitStates.Unlock()");
    writer.block("if socketEmitStates.states[rawSocket] != state", () => writer.line("return"));
    writer.line("state.refs--");
    writer.block("if state.refs == 0", () => writer.line("delete(socketEmitStates.states, rawSocket)"));
  });
}

function writeServerBinding(writer: GoWriter, methods: readonly GoRpcMethod[]): void {
  writer.block("type ServerBinding struct", () => {
    writer.line("socket    *socket.Socket");
    writer.line("emitState *socketEmitState");
    writer.line("handler   ServerHandler");
    writer.line("ctx       context.Context");
    writer.line("cancel    context.CancelFunc");
    writer.line();
    writer.line("mu          sync.RWMutex");
    writer.line("disposed    bool");
    writer.line("disposeOnce sync.Once");
    writer.line();
    const listenerNames = [...methods.map(listenerField), "listenDisconnect"];
    const listenerWidth = Math.max(...listenerNames.map((name) => name.length));
    for (const name of listenerNames) writer.line(`${padGoColumn(name, listenerWidth)}func(...any)`);
  });
  writer.line();
  writer.block(
    "func BindServer(rawSocket *socket.Socket, handler ServerHandler) (*ServerBinding, error)",
    () => {
      writer.block("if rawSocket == nil", () => writer.line('return nil, NewRpcError(CodeInvalidArgument, "socket must not be nil", "BindServer", nil)'));
      writer.block("if handler == nil", () => writer.line('return nil, NewRpcError(CodeInvalidArgument, "handler must not be nil", "BindServer", nil)'));
      writer.line("ctx, cancel := context.WithCancel(context.Background())");
      writer.line("binding := &ServerBinding{");
      writer.line("\tsocket:    rawSocket,");
      writer.line("\temitState: acquireSocketEmitState(rawSocket),");
      writer.line("\thandler:   handler,");
      writer.line("\tctx:       ctx,");
      writer.line("\tcancel:    cancel,");
      writer.line("}");
      writer.line();
      for (const method of methods) {
        const field = listenerField(method);
        writer.block(`binding.${field} = func(rawArgs ...any)`, () => {
          writer.line("args := append([]any(nil), rawArgs...)");
          writer.line(`go binding.handle${methodName(method)}(args)`);
        });
        writer.block(`if err := rawSocket.On(${goString(method.name)}, binding.${field}); err != nil`, () => {
          writer.line("binding.Dispose()");
          writer.line(`return nil, fmt.Errorf("register ${method.name}: %w", err)`);
        });
      }
      writer.block("binding.listenDisconnect = func(...any)", () => writer.line("binding.Dispose()"));
      writer.block('if err := rawSocket.On("disconnect", binding.listenDisconnect); err != nil', () => {
        writer.line("binding.Dispose()");
        writer.line('return nil, fmt.Errorf("register disconnect: %w", err)');
      });
      writer.line("return binding, nil");
    },
  );
  writer.line();
  writer.block("func (b *ServerBinding) Context() context.Context", () => writer.line("return b.ctx"));
  writer.line();
  writer.block("func (b *ServerBinding) Disposed() bool", () => {
    writer.line("b.mu.RLock()");
    writer.line("defer b.mu.RUnlock()");
    writer.line("return b.disposed");
  });
  writer.line();
  writer.block("func (b *ServerBinding) Dispose()", () => {
    writer.block("if b == nil", () => writer.line("return"));
    writer.block("b.disposeOnce.Do(func()", () => {
      writer.block("if b.emitState != nil", () => {
        writer.line("b.emitState.mu.Lock()");
        writer.line("defer b.emitState.mu.Unlock()");
      });
      writer.line("b.mu.Lock()");
      writer.line("b.disposed = true");
      writer.line("b.mu.Unlock()");
      writer.line("b.cancel()");
      for (const method of methods) {
        const field = listenerField(method);
        writer.block(`if b.socket != nil && b.${field} != nil`, () => {
          writer.line(`b.socket.RemoveListener(${goString(method.name)}, b.${field})`);
        });
      }
      writer.block("if b.socket != nil && b.listenDisconnect != nil", () => {
        writer.line('b.socket.RemoveListener("disconnect", b.listenDisconnect)');
      });
      writer.line("releaseSocketEmitState(b.socket, b.emitState)");
    }, "})");
  });
  writer.line();
  writer.block("func (b *ServerBinding) emitError(err *RpcError)", () => {
    writer.block("if err == nil || b.socket == nil || b.emitState == nil || b.Disposed()", () => writer.line("return"));
    writer.line("b.emitState.mu.Lock()");
    writer.line("defer b.emitState.mu.Unlock()");
    writer.block("if !b.socket.Connected() || b.Disposed()", () => writer.line("return"));
    writer.line("_ = b.socket.Emit(RPCErrorEvent, err)");
  });
  writer.line();
  writer.block(
    "func inboundAck(rawArgs []any, want int, origin string) (socket.Ack, []any, *RpcError)",
    () => {
      writer.block("if len(rawArgs) == 0", () => {
        writer.line('return nil, nil, NewRpcError(CodeInvalidArgument, "missing acknowledgement callback", origin, nil)');
      });
      writer.line("ack, ok := rawArgs[len(rawArgs)-1].(socket.Ack)");
      writer.block("if !ok", () => {
        writer.line('return nil, nil, NewRpcError(CodeInvalidArgument, "missing acknowledgement callback", origin, nil)');
      });
      writer.line("payload := rawArgs[:len(rawArgs)-1]");
      writer.block("if len(payload) != want", () => {
        writer.line('message := fmt.Sprintf("expected %d arguments, got %d", want, len(payload))');
        writer.line("return ack, nil, NewRpcError(CodeInvalidArgument, message, origin, nil)");
      });
      writer.line("return ack, payload, nil");
    },
  );
}

function writeDecodeParams(
  writer: GoWriter,
  method: GoRpcMethod,
  onError: (messageExpression: string) => void,
): void {
  method.params.forEach((param, index) => {
    const name = paramName(param);
    writer.line(`var ${name} ${goType(param.type)}`);
    writer.block(`if err := decodeValue(rawArgs[${index}], &${name}); err != nil`, () => {
      const message = `fmt.Sprintf("invalid argument ${param.name}: %v", err)`;
      onError(message);
    });
  });
}

function writeInboundHandlers(writer: GoWriter, methods: readonly GoRpcMethod[]): void {
  for (const method of methods) {
    const origin = goString(method.name);
    writer.line();
    writer.block(`func (b *ServerBinding) handle${methodName(method)}(rawArgs []any)`, () => {
      if (method.result) {
        writer.line(`ack, rawArgs, protocolErr := inboundAck(rawArgs, ${method.params.length}, ${origin})`);
        writer.block("if ack == nil", () => {
          writer.line("b.emitError(protocolErr)");
          writer.line("return");
        });
        writer.line("var ackOnce sync.Once");
        writer.block("reply := func(value any)", () => {
          writer.block("ackOnce.Do(func()", () => writer.line("ack([]any{value}, nil)"), "})");
        });
        writer.block("defer func()", () => {
          writer.block("if value := recover(); value != nil", () => {
            writer.line(`reply(rpcErrorFromPanic(value, ${origin}))`);
          });
        }, "}()");
        writer.block("if protocolErr != nil", () => {
          writer.line("reply(protocolErr)");
          writer.line("return");
        });
        writer.block("if b.Disposed()", () => {
          writer.line(`reply(NewRpcError(CodeDisposed, "server binding is disposed", ${origin}, nil))`);
          writer.line("return");
        });
        writeDecodeParams(writer, method, (message) => {
          writer.line(`reply(NewRpcError(CodeInvalidArgument, ${message}, ${origin}, nil))`);
          writer.line("return");
        });
        writer.line(`result, err := b.handler.${methodName(method)}(${callArguments(method)})`);
        writer.block("if err != nil", () => {
          writer.line(`reply(rpcErrorFromError(err, ${origin}))`);
          writer.line("return");
        });
        writer.line("reply(result)");
        return;
      }

      writer.block("defer func()", () => {
        writer.block("if value := recover(); value != nil", () => {
          writer.line(`b.emitError(rpcErrorFromPanic(value, ${origin}))`);
        });
      }, "}()");
      writer.block(`if len(rawArgs) != ${method.params.length}`, () => {
        writer.line(`message := fmt.Sprintf("expected %d arguments, got %d", ${method.params.length}, len(rawArgs))`);
        writer.line(`b.emitError(NewRpcError(CodeInvalidArgument, message, ${origin}, nil))`);
        writer.line("return");
      });
      writer.block("if b.Disposed()", () => writer.line("return"));
      writeDecodeParams(writer, method, (message) => {
        writer.line(`b.emitError(NewRpcError(CodeInvalidArgument, ${message}, ${origin}, nil))`);
        writer.line("return");
      });
      writer.block(`if err := b.handler.${methodName(method)}(${callArguments(method)}); err != nil`, () => {
        writer.line(`b.emitError(rpcErrorFromError(err, ${origin}))`);
      });
    });
  }
}

function writeClient(writer: GoWriter, methods: readonly GoRpcMethod[], defaultTimeoutMs: number): void {
  writer.block("type ClientOptions struct", () => writer.line("Timeout time.Duration"));
  writer.line();
  writer.block("type clientAckResult struct", () => {
    writer.line("args []any");
    writer.line("err  error");
  });
  writer.line();
  writer.block("type Client struct", () => {
    writer.line("socket    *socket.Socket");
    writer.line("emitState *socketEmitState");
    writer.line("timeout   time.Duration");
    writer.line();
    writer.line("mu sync.RWMutex");
    writer.line();
    writer.line("disposed     bool");
    writer.line("disconnected bool");
    writer.line("done         chan struct{}");
    writer.line("doneOnce     sync.Once");
    writer.line("releaseOnce  sync.Once");
    writer.line();
    writer.line("listenDisconnect func(...any)");
  });
  writer.line();
  writer.block("func NewClient(rawSocket *socket.Socket, options *ClientOptions) (*Client, error)", () => {
    writer.block("if rawSocket == nil", () => writer.line('return nil, NewRpcError(CodeInvalidArgument, "socket must not be nil", "NewClient", nil)'));
    writer.block("if options != nil && options.Timeout < 0", () => {
      writer.line('return nil, NewRpcError(CodeInvalidArgument, "timeout must not be negative", "NewClient", nil)');
    });
    writer.line(`timeout := ${defaultTimeoutMs} * time.Millisecond`);
    writer.block("if options != nil && options.Timeout > 0", () => writer.line("timeout = options.Timeout"));
    writer.line("client := &Client{");
    writer.line("\tsocket:    rawSocket,");
    writer.line("\temitState: acquireSocketEmitState(rawSocket),");
    writer.line("\ttimeout:   timeout,");
    writer.line("\tdone:      make(chan struct{}),");
    writer.line("}");
    writer.block("client.listenDisconnect = func(...any)", () => writer.line("client.markDisconnected()"));
    writer.block('if err := rawSocket.On("disconnect", client.listenDisconnect); err != nil', () => {
      writer.line("client.releaseEmitState()");
      writer.line('return nil, fmt.Errorf("register disconnect: %w", err)');
    });
    writer.block("if !rawSocket.Connected()", () => {
      writer.line("client.markDisconnected()")
      writer.line('rawSocket.RemoveListener("disconnect", client.listenDisconnect)');
      writer.line('return nil, NewRpcError(CodeDisconnected, "socket is disconnected", "NewClient", nil)');
    });
    writer.line("return client, nil");
  });
  writer.line();
  writer.block("func (c *Client) Socket() *socket.Socket", () => writer.line("return c.socket"));
  writer.line();
  writer.block("func (c *Client) Done() <-chan struct{}", () => writer.line("return c.done"));
  writer.line();
  writer.block("func (c *Client) Connected() bool", () => {
    writer.block("if c == nil", () => writer.line("return false"));
    writer.line("c.mu.RLock()");
    writer.line("defer c.mu.RUnlock()");
    writer.line("return !c.disposed && !c.disconnected && c.socket != nil && c.socket.Connected()");
  });
  writer.line();
  writer.block("func (c *Client) markDisconnected()", () => {
    writer.line("c.emitState.mu.Lock()");
    writer.line("defer c.emitState.mu.Unlock()");
    writer.line("c.mu.Lock()");
    writer.line("c.disconnected = true");
    writer.line("c.mu.Unlock()");
    writer.block("c.doneOnce.Do(func()", () => writer.line("close(c.done)"), "})");
    writer.block("if c.socket != nil && c.listenDisconnect != nil", () => {
      writer.line('c.socket.RemoveListener("disconnect", c.listenDisconnect)');
    });
    writer.line("c.releaseEmitState()");
  });
  writer.line();
  writer.block("func (c *Client) releaseEmitState()", () => {
    writer.block("c.releaseOnce.Do(func()", () => {
      writer.line("releaseSocketEmitState(c.socket, c.emitState)");
    }, "})");
  });
  writer.line();
  writer.block("func (c *Client) stateError(origin string) *RpcError", () => {
    writer.line("c.mu.RLock()");
    writer.line("defer c.mu.RUnlock()");
    writer.block("if c.disposed", () => writer.line('return NewRpcError(CodeDisposed, "client is disposed", origin, nil)'));
    writer.block("if c.disconnected || c.socket == nil || !c.socket.Connected()", () => writer.line('return NewRpcError(CodeDisconnected, "socket is disconnected", origin, nil)'));
    writer.line("return nil");
  });
  writer.line();
  writer.block("func (c *Client) Dispose()", () => {
    writer.block("if c == nil", () => writer.line("return"));
    writer.line("c.emitState.mu.Lock()");
    writer.line("defer c.emitState.mu.Unlock()");
    writer.line("c.mu.Lock()");
    writer.block("if c.disposed", () => {
      writer.line("c.mu.Unlock()");
      writer.line("return");
    });
    writer.line("c.disposed = true");
    writer.line("c.mu.Unlock()");
    writer.block("c.doneOnce.Do(func()", () => writer.line("close(c.done)"), "})");
    writer.block("if c.socket != nil && c.listenDisconnect != nil", () => {
      writer.line('c.socket.RemoveListener("disconnect", c.listenDisconnect)');
    });
    writer.line("c.releaseEmitState()");
  });
  writer.line();
  writer.block("func rpcErrorFromContext(ctx context.Context, origin string) *RpcError", () => {
    writer.block("if ctx == nil", () => writer.line('return NewRpcError(CodeInvalidArgument, "context must not be nil", origin, nil)'));
    writer.block("if err := ctx.Err(); err != nil", () => {
      writer.block("if errors.Is(err, context.DeadlineExceeded)", () => writer.line('return NewRpcError(CodeTimeout, err.Error(), origin, nil)'));
      writer.line("return NewRpcError(CodeAborted, err.Error(), origin, nil)");
    });
    writer.line("return nil");
  });
  writer.line();
  writer.block("func rpcErrorFromTransport(err error, origin string) *RpcError", () => {
    writer.block("if err == nil", () => writer.line("return nil"));
    writer.block('if err.Error() == "operation has timed out"', () => writer.line("return NewRpcError(CodeTimeout, err.Error(), origin, nil)"));
    writer.block('if err.Error() == "socket has been disconnected"', () => writer.line("return NewRpcError(CodeDisconnected, err.Error(), origin, nil)"));
    writer.line("return NewRpcError(CodeInternalError, err.Error(), origin, nil)");
  });

  for (const method of methods) writeClientMethod(writer, method);
}

function writeClientMethod(writer: GoWriter, method: GoRpcMethod): void {
  const name = methodName(method);
  const origin = goString(method.name);
  const params = methodParameters(method);
  const signatureParams = params ? `ctx context.Context, ${params}` : "ctx context.Context";
  writer.line();

  if (!method.result) {
    writer.block(`func (c *Client) ${name}(${signatureParams}) error`, () => {
      writer.block(`if err := rpcErrorFromContext(ctx, ${origin}); err != nil`, () => writer.line("return err"));
      writer.line("c.emitState.mu.Lock()");
      writer.line("defer c.emitState.mu.Unlock()");
      writer.block(`if err := c.stateError(${origin}); err != nil`, () => writer.line("return err"));
      writer.block(`if err := c.socket.Emit(${origin}${emitArguments(method)}); err != nil`, () => {
        writer.line(`return rpcErrorFromTransport(err, ${origin})`);
      });
      writer.line("return nil");
    });
    return;
  }

  const resultType = goType(method.result);
  writer.block(`func (c *Client) ${name}(${signatureParams}) (${resultType}, error)`, () => {
    writer.line(`var zero ${resultType}`);
    writer.block(`if err := rpcErrorFromContext(ctx, ${origin}); err != nil`, () => writer.line("return zero, err"));
    writer.line("response := make(chan clientAckResult, 1)");
    writer.line("c.emitState.mu.Lock()");
    writer.block(`if err := c.stateError(${origin}); err != nil`, () => {
      writer.line("c.emitState.mu.Unlock()");
      writer.line("return zero, err");
    });
    writer.line(`c.socket.Timeout(c.timeout).EmitWithAck(${origin}${emitArguments(method)})(func(args []any, err error) {`);
    writer.line("\tselect {");
    writer.line("\tcase response <- clientAckResult{args: args, err: err}:");
    writer.line("\tdefault:");
    writer.line("\t}");
    writer.line("})");
    writer.line("c.emitState.mu.Unlock()");
    writer.line();
    writer.line("var acknowledged clientAckResult");
    writer.line("select {");
    writer.line("case <-ctx.Done():");
    writer.line(`\treturn zero, rpcErrorFromContext(ctx, ${origin})`);
    writer.line("case <-c.done:");
    writer.line(`\treturn zero, c.stateError(${origin})`);
    writer.line("case acknowledged = <-response:");
    writer.line("}");
    writer.block("if acknowledged.err != nil", () => {
      writer.line(`return zero, rpcErrorFromTransport(acknowledged.err, ${origin})`);
    });
    writer.block("if len(acknowledged.args) != 1", () => {
      writer.line('message := fmt.Sprintf("expected one acknowledgement value, got %d", len(acknowledged.args))');
      writer.line(`return zero, NewRpcError(CodeInvalidArgument, message, ${origin}, nil)`);
    });
    writer.block("if rpcErr, ok := decodeRpcError(acknowledged.args[0]); ok", () => writer.line("return zero, rpcErr"));
    writer.line(`var result ${resultType}`);
    writer.block("if err := decodeValue(acknowledged.args[0], &result); err != nil", () => {
      writer.line('message := fmt.Sprintf("invalid acknowledgement payload: %v", err)');
      writer.line(`return zero, NewRpcError(CodeInvalidArgument, message, ${origin}, nil)`);
    });
    writer.line("return result, nil");
  });
}

function writeServerFile(
  schema: GoEmitterSchema,
  socketImport: string,
  defaultTimeoutMs: number,
): string {
  const writer = new GoWriter();
  writer.line(GENERATED_HEADER.trimEnd());
  writer.line();
  writer.line(`package ${schema.packageName}`);
  writer.line();
  writer.line("import (");
  writer.line('\t"context"');
  writer.line('\t"errors"');
  writer.line('\t"fmt"');
  writer.line('\t"sync"');
  writer.line('\t"time"');
  writer.line();
  writer.line(`\tsocket ${goString(socketImport)}`);
  writer.line(")");
  writer.line();
  writeSocketEmitState(writer);
  writer.line();
  writeHandlerInterface(writer, schema.clientToServer);
  writer.line();
  writeServerBinding(writer, schema.clientToServer);
  writeInboundHandlers(writer, schema.clientToServer);
  writer.line();
  writeClient(writer, schema.serverToClient, defaultTimeoutMs);
  return writer.toString();
}

/** Validate and generate deterministic, gofmt-clean Go source files. */
export function generateGo(
  schema: GoEmitterSchema,
  options: GoEmitterOptions = {},
): GeneratedGoFiles {
  validateGoEmitterSchema(schema, options);
  const socketImport = options.socketImport ?? DEFAULT_GO_SOCKET_IMPORT;
  const defaultTimeoutMs = options.defaultTimeoutMs ?? 5_000;
  return {
    [GO_TYPES_FILENAME]: writeTypesFile(schema),
    [GO_SERVER_FILENAME]: writeServerFile(schema, socketImport, defaultTimeoutMs),
  };
}

export const generateGoFiles = generateGo;
