/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.onProgress(async (update) => { ... });
 *   client.server.generate(request);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen ./define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, type Unsubscribe, toRpcError, rpcWhenAborted } from "./types.generated";

// === RpcClient INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register the handler for 'onProgress', called by the server. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    onProgress: (handler: (update: { taskId: string; progress: number; message?: string | undefined; }) => Promise<void>) => Unsubscribe;
    /** Register the handler for 'onTaskComplete', called by the server. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    onTaskComplete: (handler: (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => Promise<void>) => Unsubscribe;
    /** Register the handler for 'onError', called by the server. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    onError: (handler: (message: string, code: string) => Promise<void>) => Unsubscribe;
}

/** Methods to call server */
export interface RpcClientRemote {
    /** Call server's 'generate' method */
    generate: (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, opts?: RpcCallOptions) => Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError>;
    /** Call server's 'createTask' method */
    createTask: (request: { title: string; description?: string | undefined; }, opts?: RpcCallOptions) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
    /** Call server's 'getTask' method */
    getTask: (taskId: string, opts?: RpcCallOptions) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
    /** Call server's 'listTasks' method */
    listTasks: (opts?: RpcCallOptions) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError>;
    /** Call server's 'cancelTask' method */
    cancelTask: (taskId: string, opts?: RpcCallOptions) => void;
}

/**
 * Client RPC interface with ergonomic API.
 *
 * Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup.
 */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientRemote;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => Unsubscribe;
    /** Run a handler on every (re)connect — use it to re-sync or re-authenticate. Returns an unsubscribe function. */
    onConnect: (handler: () => void) => Unsubscribe;
    /** Run a handler after a successful reconnect. Returns an unsubscribe function. */
    onReconnect: (handler: (attempt: number) => void) => Unsubscribe;
    /** Run a handler for errors the peer reports from a fire-and-forget handler. Returns an unsubscribe function. */
    onRpcError: (handler: (error: RpcError) => void) => Unsubscribe;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.onProgress(async (update) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.generate(...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): Unsubscribe => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcClientHandle = {
        onProgress(handler: (update: { taskId: string; progress: number; message?: string | undefined; }) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (update: { taskId: string; progress: number; message?: string | undefined; }) => {
                try {
                    await handler(update);
                } catch (error) {
                    console.error('[onProgress] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'onProgress' }));
                }
            };
            return register('onProgress', listener);
        },
        onTaskComplete(handler: (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => {
                try {
                    await handler(task);
                } catch (error) {
                    console.error('[onTaskComplete] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'onTaskComplete' }));
                }
            };
            return register('onTaskComplete', listener);
        },
        onError(handler: (message: string, code: string) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (message: string, code: string) => {
                try {
                    await handler(message, code);
                } catch (error) {
                    console.error('[onError] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'onError' }));
                }
            };
            return register('onError', listener);
        }
    };

    const server: RpcClientRemote = {
        async generate(request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, opts?: RpcCallOptions): Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'generate' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'generate' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('generate', request);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'generate')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'generate' });
            }
        },
        async createTask(request: { title: string; description?: string | undefined; }, opts?: RpcCallOptions): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'createTask' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'createTask' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('createTask', request);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'createTask')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'createTask' });
            }
        },
        async getTask(taskId: string, opts?: RpcCallOptions): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'getTask' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'getTask' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('getTask', taskId);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'getTask')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'getTask' });
            }
        },
        async listTasks(opts?: RpcCallOptions): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'listTasks' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'listTasks' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('listTasks');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'listTasks')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'listTasks' });
            }
        },
        cancelTask(taskId: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('cancelTask', taskId);
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): Unsubscribe {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onConnect(handler: () => void): Unsubscribe {
            checkDisposed();
            socket.on('connect', handler);
            const unsubscribe = () => socket.off('connect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onReconnect(handler: (attempt: number) => void): Unsubscribe {
            checkDisposed();
            socket.io.on('reconnect', handler);
            const unsubscribe = () => socket.io.off('reconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onRpcError(handler: (error: RpcError) => void): Unsubscribe {
            checkDisposed();
            socket.on('__rpc:error__', handler);
            const unsubscribe = () => socket.off('__rpc:error__', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
