/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/04-zod-integration/define.ts
 */

import type { Socket } from "socket.io-client";
import type { RpcError } from "./types.generated";

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'onProgress' - called by server */
    onProgress: (handler: (update: { taskId: string; progress: number; message?: string | undefined; }) => Promise<void | RpcError>) => void;
    /** Register handler for 'onTaskComplete' - called by server */
    onTaskComplete: (handler: (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => Promise<void | RpcError>) => void;
    /** Register handler for 'onError' - called by server */
    onError: (handler: (message: string, code: string) => Promise<void | RpcError>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'generate' method */
    generate: (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, timeout?: number) => Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError>;
    /** Call server's 'createTask' method */
    createTask: (request: { title: string; description?: string | undefined; }, timeout?: number) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
    /** Call server's 'getTask' method */
    getTask: (taskId: string, timeout?: number) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
    /** Call server's 'listTasks' method */
    listTasks: (timeout?: number) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError>;
    /** Call server's 'cancelTask' method */
    cancelTask: (taskId: string) => void;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.onProgress(async (update) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.generate(...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const handle: RpcClientHandle = {
        onProgress(handler: (update: { taskId: string; progress: number; message?: string | undefined; }) => Promise<void | RpcError>) {
            checkDisposed();
            const listener = async (update: { taskId: string; progress: number; message?: string | undefined; }) => {
                try {
                    const handlerResult = await handler(update);
                    if (handlerResult && typeof handlerResult === 'object' && 'code' in handlerResult && 'message' in handlerResult) {
                        socket.emit('rpcError', handlerResult);
                    }
                } catch (error) {
                    console.error('[onProgress] Handler error:', error);
                    socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('onProgress', listener);
            unsubscribers.push(() => socket.off('onProgress', listener));
        },
        onTaskComplete(handler: (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => Promise<void | RpcError>) {
            checkDisposed();
            const listener = async (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }) => {
                try {
                    const handlerResult = await handler(task);
                    if (handlerResult && typeof handlerResult === 'object' && 'code' in handlerResult && 'message' in handlerResult) {
                        socket.emit('rpcError', handlerResult);
                    }
                } catch (error) {
                    console.error('[onTaskComplete] Handler error:', error);
                    socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('onTaskComplete', listener);
            unsubscribers.push(() => socket.off('onTaskComplete', listener));
        },
        onError(handler: (message: string, code: string) => Promise<void | RpcError>) {
            checkDisposed();
            const listener = async (message: string, code: string) => {
                try {
                    const handlerResult = await handler(message, code);
                    if (handlerResult && typeof handlerResult === 'object' && 'code' in handlerResult && 'message' in handlerResult) {
                        socket.emit('rpcError', handlerResult);
                    }
                } catch (error) {
                    console.error('[onError] Handler error:', error);
                    socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('onError', listener);
            unsubscribers.push(() => socket.off('onError', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('rpcError', listener);
            unsubscribers.push(() => socket.off('rpcError', listener));
        }
    };

    const server: RpcClientServer = {
        async generate(request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, timeout: number = 5000): Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('generate', request);
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        },
        async createTask(request: { title: string; description?: string | undefined; }, timeout: number = 5000): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('createTask', request);
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        },
        async getTask(taskId: string, timeout: number = 5000): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('getTask', taskId);
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        },
        async listTasks(timeout: number = 5000): Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('listTasks');
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        },
        cancelTask(taskId: string) {
            socket.emit('cancelTask', taskId);
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
