/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.handle.generate(async (request) => { ... });
 *   server.client.onProgress(update);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen ./define.ts
 */

import type { Socket } from "socket.io";
import { type RpcError, type RpcCallOptions, type Unsubscribe, toRpcError } from "./types.generated";

// === RpcServer INTERFACE ===
/** Handler registration methods - implement these to handle calls from client */
export interface RpcServerHandle {
    /** Register the handler for 'generate', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    generate: (handler: (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }) => Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; }>) => Unsubscribe;
    /** Register the handler for 'createTask', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    createTask: (handler: (request: { title: string; description?: string | undefined; }) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }>) => Unsubscribe;
    /** Register the handler for 'getTask', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    getTask: (handler: (taskId: string) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }>) => Unsubscribe;
    /** Register the handler for 'listTasks', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    listTasks: (handler: () => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[]>) => Unsubscribe;
    /** Register the handler for 'cancelTask', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    cancelTask: (handler: (taskId: string) => Promise<void>) => Unsubscribe;
}

/** Methods to call client */
export interface RpcServerRemote {
    /** Call client's 'onProgress' method */
    onProgress: (update: { taskId: string; progress: number; message?: string | undefined; }, opts?: RpcCallOptions) => void;
    /** Call client's 'onTaskComplete' method */
    onTaskComplete: (task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }, opts?: RpcCallOptions) => void;
    /** Call client's 'onError' method */
    onError: (message: string, code: string, opts?: RpcCallOptions) => void;
}

/**
 * Server RPC interface with ergonomic API.
 *
 * Use `.handle` to register handlers, `.client` to call client methods, and `.dispose()` to cleanup.
 */
export interface RpcServer {
    /** Register handlers for calls from client */
    readonly handle: RpcServerHandle;
    /** Call client methods */
    readonly client: RpcServerRemote;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => Unsubscribe;
    /** Run a handler for errors the peer reports from a fire-and-forget handler. Returns an unsubscribe function. */
    onRpcError: (handler: (error: RpcError) => void) => Unsubscribe;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers for calls from client
 * server.handle.generate(async (request) => {
 *   // handle event
 * });
 *
 * // Call client methods
 * server.client.onProgress(...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .handle, .client, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): Unsubscribe => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcServerHandle = {
        generate(handler: (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }) => Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; }>): Unsubscribe {
            checkDisposed();
            const listener = async (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, callback: (result: { text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler(request);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[generate] Handler error:', error);
                    callback(toRpcError(error, { method: 'generate' }));
                }
            };
            return register('generate', listener);
        },
        createTask(handler: (request: { title: string; description?: string | undefined; }) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }>): Unsubscribe {
            checkDisposed();
            const listener = async (request: { title: string; description?: string | undefined; }, callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler(request);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[createTask] Handler error:', error);
                    callback(toRpcError(error, { method: 'createTask' }));
                }
            };
            return register('createTask', listener);
        },
        getTask(handler: (taskId: string) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }>): Unsubscribe {
            checkDisposed();
            const listener = async (taskId: string, callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler(taskId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getTask] Handler error:', error);
                    callback(toRpcError(error, { method: 'getTask' }));
                }
            };
            return register('getTask', listener);
        },
        listTasks(handler: () => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[]>): Unsubscribe {
            checkDisposed();
            const listener = async (callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[listTasks] Handler error:', error);
                    callback(toRpcError(error, { method: 'listTasks' }));
                }
            };
            return register('listTasks', listener);
        },
        cancelTask(handler: (taskId: string) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (taskId: string) => {
                try {
                    await handler(taskId);
                } catch (error) {
                    console.error('[cancelTask] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'cancelTask' }));
                }
            };
            return register('cancelTask', listener);
        }
    };

    const client: RpcServerRemote = {
        onProgress(update: { taskId: string; progress: number; message?: string | undefined; }, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onProgress', update);
        },
        onTaskComplete(task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onTaskComplete', task);
        },
        onError(message: string, code: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onError', message, code);
        }
    };

    return {
        handle,
        client,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): Unsubscribe {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onRpcError(handler: (error: RpcError) => void): Unsubscribe {
            checkDisposed();
            socket.on('__rpc:error__', handler);
            const unsubscribe = () => socket.off('__rpc:error__', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
