/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server functions from define.ts
 * These functions allow SERVER to call CLIENT functions (ClientFunctions interface)
 * and set up handlers for SERVER functions (ServerFunctions interface)
 *
 * To regenerate this file, run:
 * bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/04-zod-integration/define.ts
 */

import type { Socket } from "socket.io";
import type { RpcError, UnsubscribeFunction } from "./types.generated";

// === SERVER HANDLER TYPES ===
/** Handler type for processing 'generate' events from client */
export type GenerateHandler = (socket: Socket, request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }) => Promise<{ text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError>;
/** Handler type for processing 'createTask' events from client */
export type CreateTaskHandler = (socket: Socket, request: { title: string; description?: string | undefined; }) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
/** Handler type for processing 'getTask' events from client */
export type GetTaskHandler = (socket: Socket, taskId: string) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError>;
/** Handler type for processing 'listTasks' events from client */
export type ListTasksHandler = (socket: Socket) => Promise<{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError>;
/** Handler type for processing 'cancelTask' events from client */
export type CancelTaskHandler = (socket: Socket, taskId: string) => Promise<void | RpcError>;

// === SERVER CALLING CLIENT FUNCTIONS ===
/**
 * SERVER calls CLIENT: Emits 'onProgress' event to client without acknowledgment. Includes built-in error handling.
 * @param {Socket} socket The socket instance for communication.
 * @param {{ taskId: string; progress: number; message?: string | undefined; }} update
 */
export function onProgress(socket: Socket, update: { taskId: string; progress: number; message?: string | undefined; }): void {
    socket.emit('onProgress', update);
}

/**
 * SERVER calls CLIENT: Emits 'onTaskComplete' event to client without acknowledgment. Includes built-in error handling.
 * @param {Socket} socket The socket instance for communication.
 * @param {{ id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }} task
 */
export function onTaskComplete(socket: Socket, task: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }): void {
    socket.emit('onTaskComplete', task);
}

/**
 * SERVER calls CLIENT: Emits 'onError' event to client without acknowledgment. Includes built-in error handling.
 * @param {Socket} socket The socket instance for communication.
 * @param {string} message
 * @param {string} code
 */
export function onError(socket: Socket, message: string, code: string): void {
    socket.emit('onError', message, code);
}

// === SERVER HANDLER FUNCTIONS ===
/**
 * Sets up listener for 'generate' events from client with acknowledgment. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {GenerateHandler} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleGenerate(socket: Socket, handler: GenerateHandler): UnsubscribeFunction {
    const listener = async (request: { prompt: string; maxTokens?: number | undefined; temperature?: number | undefined; }, callback: (result: { text: string; finishReason: "stop" | "length" | "content_filter"; usage: { inputTokens: number; outputTokens: number; }; } | RpcError) => void) => {
        try {
            const result = await handler(socket, request);
            callback(result);
        } catch (error) {
            console.error('[generate] Handler error:', error);
            callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
        }
    };
    socket.on('generate', listener);
    return () => socket.off('generate', listener);
}

/**
 * Sets up listener for 'createTask' events from client with acknowledgment. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {CreateTaskHandler} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleCreateTask(socket: Socket, handler: CreateTaskHandler): UnsubscribeFunction {
    const listener = async (request: { title: string; description?: string | undefined; }, callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError) => void) => {
        try {
            const result = await handler(socket, request);
            callback(result);
        } catch (error) {
            console.error('[createTask] Handler error:', error);
            callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
        }
    };
    socket.on('createTask', listener);
    return () => socket.off('createTask', listener);
}

/**
 * Sets up listener for 'getTask' events from client with acknowledgment. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {GetTaskHandler} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleGetTask(socket: Socket, handler: GetTaskHandler): UnsubscribeFunction {
    const listener = async (taskId: string, callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; } | RpcError) => void) => {
        try {
            const result = await handler(socket, taskId);
            callback(result);
        } catch (error) {
            console.error('[getTask] Handler error:', error);
            callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
        }
    };
    socket.on('getTask', listener);
    return () => socket.off('getTask', listener);
}

/**
 * Sets up listener for 'listTasks' events from client with acknowledgment. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {ListTasksHandler} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleListTasks(socket: Socket, handler: ListTasksHandler): UnsubscribeFunction {
    const listener = async (callback: (result: { id: string; title: string; description: string; status: "pending" | "in_progress" | "completed"; createdAt: string; }[] | RpcError) => void) => {
        try {
            const result = await handler(socket);
            callback(result);
        } catch (error) {
            console.error('[listTasks] Handler error:', error);
            callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
        }
    };
    socket.on('listTasks', listener);
    return () => socket.off('listTasks', listener);
}

/**
 * Sets up listener for 'cancelTask' events from client. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {CancelTaskHandler} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleCancelTask(socket: Socket, handler: CancelTaskHandler): UnsubscribeFunction {
    const listener = async (taskId: string) => {
        try {
            const result = await handler(socket, taskId);
            if (result && typeof result === 'object' && 'code' in result && 'message' in result) {
                socket.emit('rpcError', result);
            }
        } catch (error) {
            console.error('[cancelTask] Handler error:', error);
            socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
        }
    };
    socket.on('cancelTask', listener);
    return () => socket.off('cancelTask', listener);
}

/**
 * Sets up listener for 'rpcError' events with async/await and try-catch. This handler is called whenever an RPC error occurs during function execution. Returns a function to remove the listener.
 * @param {Socket} socket The socket instance for communication.
 * @param {(socket: Socket, error: RpcError) => Promise<void>} handler The handler function to process incoming events.
 * @returns {UnsubscribeFunction} A function that removes the event listener when called
 */
export function handleRpcError(socket: Socket, handler: (socket: Socket, error: RpcError) => Promise<void>): UnsubscribeFunction {
    const listener = async (error: RpcError) => {
        try {
            await handler(socket, error);
        } catch (handlerError) {
            console.error('[handleRpcError] Error in RPC error handler:', handlerError);
        }
    };
    socket.on('rpcError', listener);
    return () => socket.off('rpcError', listener);
}
