/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.on.eventName(async (data) => { ... });
 *   server.call.methodName(args);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/01-basic/define.ts
 */

import type { Socket } from "socket.io";
import type { RpcError } from "./types.generated";
import type { User } from "./define";

// === RPCSERVER INTERFACE ===
/** Handler registration methods for server */
export interface RpcServerOn {
    /** Register handler for 'getUser' events from client */
    getUser: (handler: (userId: string) => Promise<User | RpcError>) => void;
    /** Register handler for 'createUser' events from client */
    createUser: (handler: (name: string, email: string) => Promise<User | RpcError>) => void;
    /** Register handler for 'deleteUser' events from client */
    deleteUser: (handler: (userId: string) => Promise<void | RpcError>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** RPC call methods for server to call client */
export interface RpcServerCall {
    /** Call client's 'onMessage' method */
    onMessage: (message: string) => void;
    /** Call client's 'requestConfirmation' method */
    requestConfirmation: (prompt: string, timeout?: number) => Promise<boolean | RpcError>;
}

/** Server RPC interface with ergonomic API. */
/** Use `.on` to register handlers, `.call` to make RPC calls, and `.dispose()` to cleanup. */
export interface RpcServer {
    /** Register handlers for incoming events */
    readonly on: RpcServerOn;
    /** Call client methods */
    readonly call: RpcServerCall;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers
 * server.on.getUser(async (userId) => {
 *   // handle event
 * });
 *
 * // Make calls
 * server.call.onMessage(...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .on, .call, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const on: RpcServerOn = {
        getUser(handler: (userId: string) => Promise<User | RpcError>) {
            checkDisposed();
            const listener = async (userId: string, callback: (result: User | RpcError) => void) => {
                try {
                    const result = await handler(userId);
                    callback(result);
                } catch (error) {
                    console.error('[getUser] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('getUser', listener);
            unsubscribers.push(() => socket.off('getUser', listener));
        },
        createUser(handler: (name: string, email: string) => Promise<User | RpcError>) {
            checkDisposed();
            const listener = async (name: string, email: string, callback: (result: User | RpcError) => void) => {
                try {
                    const result = await handler(name, email);
                    callback(result);
                } catch (error) {
                    console.error('[createUser] Handler error:', error);
                    callback({ message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('createUser', listener);
            unsubscribers.push(() => socket.off('createUser', listener));
        },
        deleteUser(handler: (userId: string) => Promise<void | RpcError>) {
            checkDisposed();
            const listener = async (userId: string) => {
                try {
                    const result = await handler(userId);
                    if (result && typeof result === 'object' && 'code' in result && 'message' in result) {
                        socket.emit('rpcError', result);
                    }
                } catch (error) {
                    console.error('[deleteUser] Handler error:', error);
                    socket.emit('rpcError', { message: error instanceof Error ? error.message : String(error), code: 'INTERNAL_ERROR', data: undefined });
                }
            };
            socket.on('deleteUser', listener);
            unsubscribers.push(() => socket.off('deleteUser', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('rpcError', listener);
            unsubscribers.push(() => socket.off('rpcError', listener));
        }
    };

    const call: RpcServerCall = {
        onMessage(message: string) {
            socket.emit('onMessage', message);
        },
        async requestConfirmation(prompt: string, timeout: number = 5000): Promise<boolean | RpcError> {
            try {
                return await socket.timeout(timeout).emitWithAck('requestConfirmation', prompt);
            } catch (err) {
                return { message: err instanceof Error ? err.message : String(err), code: 'INTERNAL_ERROR', data: undefined };
            }
        }
    };

    return {
        on,
        call,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
