/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.handle.getUser(async (userId) => { ... });
 *   server.client.onMessage(message);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen ./define.ts
 */

import type { Socket } from "socket.io";
import { type RpcError, type RpcCallOptions, type Unsubscribe, toRpcError, rpcWhenAborted } from "./types.generated";
import type { User } from "./define";

// === RpcServer INTERFACE ===
/** Handler registration methods - implement these to handle calls from client */
export interface RpcServerHandle {
    /** Register the handler for 'getUser', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    getUser: (handler: (userId: string) => Promise<User>) => Unsubscribe;
    /** Register the handler for 'createUser', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    createUser: (handler: (name: string, email: string) => Promise<User>) => Unsubscribe;
    /** Register the handler for 'deleteUser', called by the client. Re-registering replaces the previous handler. Returns an unsubscribe function. */
    deleteUser: (handler: (userId: string) => Promise<void>) => Unsubscribe;
}

/** Methods to call client */
export interface RpcServerRemote {
    /** Call client's 'onMessage' method */
    onMessage: (message: string, opts?: RpcCallOptions) => void;
    /** Call client's 'requestConfirmation' method */
    requestConfirmation: (prompt: string, opts?: RpcCallOptions) => Promise<boolean | RpcError>;
}

/**
 * Server RPC interface with ergonomic API.
 *
 * Use `.handle` to register handlers, `.client` to call client methods, and `.dispose()` to cleanup.
 */
export interface RpcServer {
    /** Register handlers for calls from client */
    readonly handle: RpcServerHandle;
    /** Call client methods */
    readonly client: RpcServerRemote;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => Unsubscribe;
    /** Run a handler for errors the peer reports from a fire-and-forget handler. Returns an unsubscribe function. */
    onRpcError: (handler: (error: RpcError) => void) => Unsubscribe;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers for calls from client
 * server.handle.getUser(async (userId) => {
 *   // handle event
 * });
 *
 * // Call client methods
 * server.client.onMessage(...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .handle, .client, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): Unsubscribe => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcServerHandle = {
        getUser(handler: (userId: string) => Promise<User>): Unsubscribe {
            checkDisposed();
            const listener = async (userId: string, callback: (result: User | RpcError) => void) => {
                try {
                    const handlerResult = await handler(userId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getUser] Handler error:', error);
                    callback(toRpcError(error, { method: 'getUser' }));
                }
            };
            return register('getUser', listener);
        },
        createUser(handler: (name: string, email: string) => Promise<User>): Unsubscribe {
            checkDisposed();
            const listener = async (name: string, email: string, callback: (result: User | RpcError) => void) => {
                try {
                    const handlerResult = await handler(name, email);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[createUser] Handler error:', error);
                    callback(toRpcError(error, { method: 'createUser' }));
                }
            };
            return register('createUser', listener);
        },
        deleteUser(handler: (userId: string) => Promise<void>): Unsubscribe {
            checkDisposed();
            const listener = async (userId: string) => {
                try {
                    await handler(userId);
                } catch (error) {
                    console.error('[deleteUser] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { method: 'deleteUser' }));
                }
            };
            return register('deleteUser', listener);
        }
    };

    const client: RpcServerRemote = {
        onMessage(message: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onMessage', message);
        },
        async requestConfirmation(prompt: string, opts?: RpcCallOptions): Promise<boolean | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', method: 'requestConfirmation' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', method: 'requestConfirmation' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('requestConfirmation', prompt);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'requestConfirmation')]) : ack);
            } catch (err) {
                return toRpcError(err, { method: 'requestConfirmation' });
            }
        }
    };

    return {
        handle,
        client,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): Unsubscribe {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        onRpcError(handler: (error: RpcError) => void): Unsubscribe {
            checkDisposed();
            socket.on('__rpc:error__', handler);
            const unsubscribe = () => socket.off('__rpc:error__', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
