/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated client RPC from define.ts
 *
 * Usage:
 *   const client = createRpcClient(socket);
 *   client.handle.eventName(async (data) => { ... });
 *   client.server.methodName(args);
 *   client.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/03-multi-level-extension/define.ts
 */

import type { Socket } from "socket.io-client";
import { type RpcError, type RpcCallOptions, toRpcError } from "./types.generated";
import type { Order, CreateOrderRequest, OrderStatusUpdate } from "./define";
import type { User, AuthToken } from "./platform.define";

// === RPCCLIENT INTERFACE ===
/** Handler registration methods - implement these to handle calls from server */
export interface RpcClientHandle {
    /** Register handler for 'showNotification' - called by server */
    showNotification: (handler: (title: string, message: string) => Promise<void>) => void;
    /** Register handler for 'requestAuth' - called by server */
    requestAuth: (handler: () => Promise<AuthToken | null>) => void;
    /** Register handler for 'log' - called by server */
    log: (handler: (level: "info" | "warn" | "error", message: string) => Promise<void>) => void;
    /** Register handler for 'getVersion' - called by server */
    getVersion: (handler: () => Promise<string>) => void;
    /** Register handler for 'onOrderStatusChanged' - called by server */
    onOrderStatusChanged: (handler: (update: OrderStatusUpdate) => Promise<void>) => void;
    /** Register handler for 'refreshOrderList' - called by server */
    refreshOrderList: (handler: () => Promise<void>) => void;
    /** Register handler for 'confirmPayment' - called by server */
    confirmPayment: (handler: (amount: number) => Promise<boolean>) => void;
    /** Register handler for RPC errors */
    rpcError: (handler: (error: RpcError) => void) => void;
}

/** Methods to call server */
export interface RpcClientServer {
    /** Call server's 'login' method */
    login: (username: string, password: string, opts?: RpcCallOptions) => Promise<{ user: User; token: AuthToken; } | RpcError>;
    /** Call server's 'getCurrentUser' method */
    getCurrentUser: (opts?: RpcCallOptions) => Promise<User | RpcError>;
    /** Call server's 'logout' method */
    logout: () => void;
    /** Call server's 'healthCheck' method */
    healthCheck: (opts?: RpcCallOptions) => Promise<{ status: "ok" | "degraded"; timestamp: number; } | RpcError>;
    /** Call server's 'getOrder' method */
    getOrder: (orderId: string, opts?: RpcCallOptions) => Promise<Order | RpcError>;
    /** Call server's 'createOrder' method */
    createOrder: (request: CreateOrderRequest, opts?: RpcCallOptions) => Promise<Order | RpcError>;
    /** Call server's 'cancelOrder' method */
    cancelOrder: (orderId: string, opts?: RpcCallOptions) => Promise<Order | RpcError>;
    /** Call server's 'listOrders' method */
    listOrders: (userId: string, opts?: RpcCallOptions) => Promise<Order[] | RpcError>;
}

/** Client RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.server` to call server methods, and `.dispose()` to cleanup. */
export interface RpcClient {
    /** Register handlers for calls from server */
    readonly handle: RpcClientHandle;
    /** Call server methods */
    readonly server: RpcClientServer;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a client RPC instance.
 *
 * Usage:
 * ```typescript
 * const client = createRpcClient(socket);
 *
 * // Register handlers for calls from server
 * client.handle.showNotification(async (title, message) => {
 *   // handle event
 * });
 *
 * // Call server methods
 * const result = await client.server.login(..., ...);
 *
 * // Cleanup when done
 * client.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcClient instance with .handle, .server, and .dispose()
 */
export function createRpcClient(socket: Socket): RpcClient {
    const unsubscribers: Array<() => void> = [];
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcClient has been disposed');
    };

    const handle: RpcClientHandle = {
        showNotification(handler: (title: string, message: string) => Promise<void>) {
            checkDisposed();
            const listener = async (title: string, message: string) => {
                try {
                    await handler(title, message);
                } catch (error) {
                    console.error('[showNotification] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'showNotification' }));
                }
            };
            socket.on('showNotification', listener);
            unsubscribers.push(() => socket.off('showNotification', listener));
        },
        requestAuth(handler: () => Promise<AuthToken | null>) {
            checkDisposed();
            const listener = async (callback: (result: AuthToken | null | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[requestAuth] Handler error:', error);
                    callback(toRpcError(error, { origin: 'requestAuth' }));
                }
            };
            socket.on('requestAuth', listener);
            unsubscribers.push(() => socket.off('requestAuth', listener));
        },
        log(handler: (level: "info" | "warn" | "error", message: string) => Promise<void>) {
            checkDisposed();
            const listener = async (level: "info" | "warn" | "error", message: string) => {
                try {
                    await handler(level, message);
                } catch (error) {
                    console.error('[log] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'log' }));
                }
            };
            socket.on('log', listener);
            unsubscribers.push(() => socket.off('log', listener));
        },
        getVersion(handler: () => Promise<string>) {
            checkDisposed();
            const listener = async (callback: (result: string | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getVersion] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getVersion' }));
                }
            };
            socket.on('getVersion', listener);
            unsubscribers.push(() => socket.off('getVersion', listener));
        },
        onOrderStatusChanged(handler: (update: OrderStatusUpdate) => Promise<void>) {
            checkDisposed();
            const listener = async (update: OrderStatusUpdate) => {
                try {
                    await handler(update);
                } catch (error) {
                    console.error('[onOrderStatusChanged] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'onOrderStatusChanged' }));
                }
            };
            socket.on('onOrderStatusChanged', listener);
            unsubscribers.push(() => socket.off('onOrderStatusChanged', listener));
        },
        refreshOrderList(handler: () => Promise<void>) {
            checkDisposed();
            const listener = async () => {
                try {
                    await handler();
                } catch (error) {
                    console.error('[refreshOrderList] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'refreshOrderList' }));
                }
            };
            socket.on('refreshOrderList', listener);
            unsubscribers.push(() => socket.off('refreshOrderList', listener));
        },
        confirmPayment(handler: (amount: number) => Promise<boolean>) {
            checkDisposed();
            const listener = async (amount: number, callback: (result: boolean | RpcError) => void) => {
                try {
                    const handlerResult = await handler(amount);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[confirmPayment] Handler error:', error);
                    callback(toRpcError(error, { origin: 'confirmPayment' }));
                }
            };
            socket.on('confirmPayment', listener);
            unsubscribers.push(() => socket.off('confirmPayment', listener));
        },
        rpcError(handler: (error: RpcError) => void) {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            socket.on('__rpc:error__', listener);
            unsubscribers.push(() => socket.off('__rpc:error__', listener));
        }
    };

    const server: RpcClientServer = {
        async login(username: string, password: string, opts?: RpcCallOptions): Promise<{ user: User; token: AuthToken; } | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'login' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('login', username, password);
            } catch (err) {
                return toRpcError(err, { origin: 'login' });
            }
        },
        async getCurrentUser(opts?: RpcCallOptions): Promise<User | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getCurrentUser' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('getCurrentUser');
            } catch (err) {
                return toRpcError(err, { origin: 'getCurrentUser' });
            }
        },
        logout() {
            if (_disposed) return;
            socket.emit('logout');
        },
        async healthCheck(opts?: RpcCallOptions): Promise<{ status: "ok" | "degraded"; timestamp: number; } | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'healthCheck' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('healthCheck');
            } catch (err) {
                return toRpcError(err, { origin: 'healthCheck' });
            }
        },
        async getOrder(orderId: string, opts?: RpcCallOptions): Promise<Order | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getOrder' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('getOrder', orderId);
            } catch (err) {
                return toRpcError(err, { origin: 'getOrder' });
            }
        },
        async createOrder(request: CreateOrderRequest, opts?: RpcCallOptions): Promise<Order | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'createOrder' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('createOrder', request);
            } catch (err) {
                return toRpcError(err, { origin: 'createOrder' });
            }
        },
        async cancelOrder(orderId: string, opts?: RpcCallOptions): Promise<Order | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'cancelOrder' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('cancelOrder', orderId);
            } catch (err) {
                return toRpcError(err, { origin: 'cancelOrder' });
            }
        },
        async listOrders(userId: string, opts?: RpcCallOptions): Promise<Order[] | RpcError> {
            if (_disposed) return { message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'listOrders' };
            const timeout = opts?.timeout ?? 5000;
            try {
                return await socket.timeout(timeout).emitWithAck('listOrders', userId);
            } catch (err) {
                return toRpcError(err, { origin: 'listOrders' });
            }
        }
    };

    return {
        handle,
        server,
        get socket() { return socket; },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
        }
    };
}
