/**
 * ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
 *
 * Auto-generated server RPC from define.ts
 *
 * Usage:
 *   const server = createRpcServer(socket);
 *   server.handle.eventName(async (data) => { ... });
 *   server.client.methodName(args);
 *   server.dispose();
 *
 * To regenerate: bunx socketrpc-gen /Volumes/Data/Projects/socket-rpc/examples/03-multi-level-extension/define.ts
 */

import type { Socket } from "socket.io";
import { type RpcError, type RpcCallOptions, type UnsubscribeFunction, toRpcError, rpcWhenAborted } from "./types.generated";
import type { Order, CreateOrderRequest, OrderStatusUpdate } from "./define";
import type { User, AuthToken } from "./platform.define";

// === SOCKET EVENT MAPS (optional typing aid) ===
/** Events the client emits and the server listens for. Apply to a typed Socket/Server. */
export interface ClientToServerEvents {
    login: (username: string, password: string, ack: (result: { user: User; token: AuthToken; } | RpcError) => void) => void;
    getCurrentUser: (ack: (result: User | RpcError) => void) => void;
    logout: () => void;
    healthCheck: (ack: (result: { status: "ok" | "degraded"; timestamp: number; } | RpcError) => void) => void;
    getOrder: (orderId: string, ack: (result: Order | RpcError) => void) => void;
    createOrder: (request: CreateOrderRequest, ack: (result: Order | RpcError) => void) => void;
    cancelOrder: (orderId: string, ack: (result: Order | RpcError) => void) => void;
    listOrders: (userId: string, ack: (result: Order[] | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

/** Events the server emits and the client listens for. Apply to a typed Socket/Server. */
export interface ServerToClientEvents {
    showNotification: (title: string, message: string) => void;
    requestAuth: (ack: (result: AuthToken | null | RpcError) => void) => void;
    log: (level: "info" | "warn" | "error", message: string) => void;
    getVersion: (ack: (result: string | RpcError) => void) => void;
    onOrderStatusChanged: (update: OrderStatusUpdate) => void;
    refreshOrderList: () => void;
    confirmPayment: (amount: number, ack: (result: boolean | RpcError) => void) => void;
    "__rpc:error__": (error: RpcError) => void;
}

// === RPCSERVER INTERFACE ===
/** Handler registration methods - implement these to handle calls from client */
export interface RpcServerHandle {
    /** Register handler for 'login' - called by client. Returns an unsubscribe function. */
    login: (handler: (username: string, password: string) => Promise<{ user: User; token: AuthToken; }>) => UnsubscribeFunction;
    /** Register handler for 'getCurrentUser' - called by client. Returns an unsubscribe function. */
    getCurrentUser: (handler: () => Promise<User>) => UnsubscribeFunction;
    /** Register handler for 'logout' - called by client. Returns an unsubscribe function. */
    logout: (handler: () => Promise<void>) => UnsubscribeFunction;
    /** Register handler for 'healthCheck' - called by client. Returns an unsubscribe function. */
    healthCheck: (handler: () => Promise<{ status: "ok" | "degraded"; timestamp: number; }>) => UnsubscribeFunction;
    /** Register handler for 'getOrder' - called by client. Returns an unsubscribe function. */
    getOrder: (handler: (orderId: string) => Promise<Order>) => UnsubscribeFunction;
    /** Register handler for 'createOrder' - called by client. Returns an unsubscribe function. */
    createOrder: (handler: (request: CreateOrderRequest) => Promise<Order>) => UnsubscribeFunction;
    /** Register handler for 'cancelOrder' - called by client. Returns an unsubscribe function. */
    cancelOrder: (handler: (orderId: string) => Promise<Order>) => UnsubscribeFunction;
    /** Register handler for 'listOrders' - called by client. Returns an unsubscribe function. */
    listOrders: (handler: (userId: string) => Promise<Order[]>) => UnsubscribeFunction;
    /** Register handler for RPC errors. Returns an unsubscribe function. */
    rpcError: (handler: (error: RpcError) => void) => UnsubscribeFunction;
}

/** Methods to call client */
export interface RpcServerClient {
    /** Call client's 'showNotification' method */
    showNotification: (title: string, message: string, opts?: RpcCallOptions) => void;
    /** Call client's 'requestAuth' method */
    requestAuth: (opts?: RpcCallOptions) => Promise<AuthToken | null | RpcError>;
    /** Call client's 'log' method */
    log: (level: "info" | "warn" | "error", message: string, opts?: RpcCallOptions) => void;
    /** Call client's 'getVersion' method */
    getVersion: (opts?: RpcCallOptions) => Promise<string | RpcError>;
    /** Call client's 'onOrderStatusChanged' method */
    onOrderStatusChanged: (update: OrderStatusUpdate, opts?: RpcCallOptions) => void;
    /** Call client's 'refreshOrderList' method */
    refreshOrderList: (opts?: RpcCallOptions) => void;
    /** Call client's 'confirmPayment' method */
    confirmPayment: (amount: number, opts?: RpcCallOptions) => Promise<boolean | RpcError>;
}

/** Server RPC interface with ergonomic API. */
/** Use `.handle` to register handlers, `.client` to call client methods, and `.dispose()` to cleanup. */
export interface RpcServer {
    /** Register handlers for calls from client */
    readonly handle: RpcServerHandle;
    /** Call client methods */
    readonly client: RpcServerClient;
    /** The underlying socket instance */
    readonly socket: Socket;
    /** Whether the underlying socket is currently connected. */
    readonly connected: boolean;
    /** Run a handler whenever the socket disconnects. Returns an unsubscribe function. */
    onDisconnect: (handler: (reason: string) => void) => UnsubscribeFunction;
    /** Whether this instance has been disposed */
    readonly disposed: boolean;
    /** Cleanup all registered handlers. Call this when done (e.g., in onBeforeUnmount or useEffect cleanup). */
    dispose(): void;
}

// === FACTORY FUNCTION ===
/**
 * Create a server RPC instance.
 *
 * Usage:
 * ```typescript
 * const server = createRpcServer(socket);
 *
 * // Register handlers for calls from client
 * server.handle.login(async (username, password) => {
 *   // handle event
 * });
 *
 * // Call client methods
 * server.client.showNotification(..., ...);
 *
 * // Cleanup when done
 * server.dispose();
 * ```
 * @param socket The socket instance
 * @returns RpcServer instance with .handle, .client, and .dispose()
 */
export function createRpcServer(socket: Socket): RpcServer {
    const unsubscribers: Array<() => void> = [];
    const handlerRegistry = new Map<string, (...args: any[]) => void>();
    let _disposed = false;

    const checkDisposed = () => {
        if (_disposed) throw new Error('RpcServer has been disposed');
    };

    const register = (event: string, listener: (...args: any[]) => void): UnsubscribeFunction => {
        const prev = handlerRegistry.get(event);
        if (prev) socket.off(event, prev);
        handlerRegistry.set(event, listener);
        socket.on(event, listener);
        const unsubscribe = () => {
            if (handlerRegistry.get(event) === listener) {
                handlerRegistry.delete(event);
                socket.off(event, listener);
            }
        };
        unsubscribers.push(unsubscribe);
        return unsubscribe;
    };

    const handle: RpcServerHandle = {
        login(handler: (username: string, password: string) => Promise<{ user: User; token: AuthToken; }>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (username: string, password: string, callback: (result: { user: User; token: AuthToken; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler(username, password);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[login] Handler error:', error);
                    callback(toRpcError(error, { origin: 'login' }));
                }
            };
            return register('login', listener);
        },
        getCurrentUser(handler: () => Promise<User>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (callback: (result: User | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getCurrentUser] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getCurrentUser' }));
                }
            };
            return register('getCurrentUser', listener);
        },
        logout(handler: () => Promise<void>): UnsubscribeFunction {
            checkDisposed();
            const listener = async () => {
                try {
                    await handler();
                } catch (error) {
                    console.error('[logout] Handler error:', error);
                    socket.emit('__rpc:error__', toRpcError(error, { origin: 'logout' }));
                }
            };
            return register('logout', listener);
        },
        healthCheck(handler: () => Promise<{ status: "ok" | "degraded"; timestamp: number; }>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (callback: (result: { status: "ok" | "degraded"; timestamp: number; } | RpcError) => void) => {
                try {
                    const handlerResult = await handler();
                    callback(handlerResult);
                } catch (error) {
                    console.error('[healthCheck] Handler error:', error);
                    callback(toRpcError(error, { origin: 'healthCheck' }));
                }
            };
            return register('healthCheck', listener);
        },
        getOrder(handler: (orderId: string) => Promise<Order>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (orderId: string, callback: (result: Order | RpcError) => void) => {
                try {
                    const handlerResult = await handler(orderId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[getOrder] Handler error:', error);
                    callback(toRpcError(error, { origin: 'getOrder' }));
                }
            };
            return register('getOrder', listener);
        },
        createOrder(handler: (request: CreateOrderRequest) => Promise<Order>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (request: CreateOrderRequest, callback: (result: Order | RpcError) => void) => {
                try {
                    const handlerResult = await handler(request);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[createOrder] Handler error:', error);
                    callback(toRpcError(error, { origin: 'createOrder' }));
                }
            };
            return register('createOrder', listener);
        },
        cancelOrder(handler: (orderId: string) => Promise<Order>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (orderId: string, callback: (result: Order | RpcError) => void) => {
                try {
                    const handlerResult = await handler(orderId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[cancelOrder] Handler error:', error);
                    callback(toRpcError(error, { origin: 'cancelOrder' }));
                }
            };
            return register('cancelOrder', listener);
        },
        listOrders(handler: (userId: string) => Promise<Order[]>): UnsubscribeFunction {
            checkDisposed();
            const listener = async (userId: string, callback: (result: Order[] | RpcError) => void) => {
                try {
                    const handlerResult = await handler(userId);
                    callback(handlerResult);
                } catch (error) {
                    console.error('[listOrders] Handler error:', error);
                    callback(toRpcError(error, { origin: 'listOrders' }));
                }
            };
            return register('listOrders', listener);
        },
        rpcError(handler: (error: RpcError) => void): UnsubscribeFunction {
            checkDisposed();
            const listener = (error: RpcError) => handler(error);
            return register('__rpc:error__', listener);
        }
    };

    const client: RpcServerClient = {
        showNotification(title: string, message: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('showNotification', title, message);
        },
        async requestAuth(opts?: RpcCallOptions): Promise<AuthToken | null | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'requestAuth' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'requestAuth' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('requestAuth');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'requestAuth')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'requestAuth' });
            }
        },
        log(level: "info" | "warn" | "error", message: string, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('log', level, message);
        },
        async getVersion(opts?: RpcCallOptions): Promise<string | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'getVersion' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'getVersion' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('getVersion');
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'getVersion')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'getVersion' });
            }
        },
        onOrderStatusChanged(update: OrderStatusUpdate, opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('onOrderStatusChanged', update);
        },
        refreshOrderList(opts?: RpcCallOptions) {
            if (_disposed) return;
            (opts?.volatile ? socket.volatile : socket).emit('refreshOrderList');
        },
        async confirmPayment(amount: number, opts?: RpcCallOptions): Promise<boolean | RpcError> {
            if (_disposed) return { __rpcError: true, message: 'RPC instance has been disposed', code: 'DISPOSED', origin: 'confirmPayment' };
            if (opts?.signal?.aborted) return { __rpcError: true, message: 'Request aborted', code: 'ABORTED', origin: 'confirmPayment' };
            const timeout = opts?.timeout ?? 5000;
            const emitter = opts?.volatile ? socket.volatile : socket;
            try {
                const ack = emitter.timeout(timeout).emitWithAck('confirmPayment', amount);
                return await (opts?.signal ? Promise.race([ack, rpcWhenAborted(opts.signal, 'confirmPayment')]) : ack);
            } catch (err) {
                return toRpcError(err, { origin: 'confirmPayment' });
            }
        }
    };

    return {
        handle,
        client,
        get socket() { return socket; },
        get connected() { return socket.connected; },
        onDisconnect(handler: (reason: string) => void): UnsubscribeFunction {
            checkDisposed();
            socket.on('disconnect', handler);
            const unsubscribe = () => socket.off('disconnect', handler);
            unsubscribers.push(unsubscribe);
            return unsubscribe;
        },
        get disposed() { return _disposed; },
        dispose() {
            if (_disposed) return;
            _disposed = true;
            unsubscribers.forEach(fn => fn());
            unsubscribers.length = 0;
            handlerRegistry.clear();
        }
    };
}
